//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    
    /// <summary>
    /// 数据库表名称：basi_station_info
    /// </summary>
    public class BasiStationInfo:INotifyPropertyChanged
    {
        
        /// <summary>
        /// 车站id
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_CN_NAME
        /// </summary>
        private string _station_cn_name;
        
        /// <summary>
        /// COLUMN: STATION_EN_NAME
        /// </summary>
        private string _station_en_name;
        
        /// <summary>
        /// COLUMN: LOCATION_TYPE
        /// </summary>
        private string _location_type;
        
        /// <summary>
        /// COLUMN: LOCATION_NUMBER
        /// </summary>
        private decimal _location_number;
        
        /// <summary>
        /// 位置id
        /// </summary>
        private string _location_id;
        
        /// <summary>
        /// COLUMN: STATION_IP
        /// </summary>
        private string _station_ip;


        private string _device_id;



        public string device_id
        {
            set { this._device_id = value; }
            get { return this._device_id; }
        }
        
        /// <summary>
        /// 车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
             
            
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_CN_NAME
        /// </summary>
        public string station_cn_name
        {
            get
            {
                return this._station_cn_name;
            }
            set
            {
                this._station_cn_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_EN_NAME
        /// </summary>
        public string station_en_name
        {
            get
            {
                return this._station_en_name;
            }
            set
            {
                this._station_en_name = value;
                this.ProperyChange("station_en_name");
            }
        }
        
        /// <summary>
        /// COLUMN: LOCATION_TYPE
        /// </summary>
        public string location_type
        {
            get
            {
                return this._location_type;
            }
            set
            {
                this._location_type = value;
                this.ProperyChange("location_type");
            }
        }
        
        /// <summary>
        /// COLUMN: LOCATION_NUMBER
        /// </summary>
        public decimal location_number
        {
            get
            {
                return this._location_number;
            }
            set
            {
                this._location_number = value;
                this.ProperyChange("location_number");
            }
        }
        
        /// <summary>
        /// 位置id
        /// </summary>
        public string location_id
        {
            get
            {
                return this._location_id;
            }
            set
            {
                this._location_id = value;
                this.ProperyChange("location_id");
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_IP
        /// </summary>
        public string station_ip
        {
            get
            {
                return this._station_ip;
            }
            set
            {
                this._station_ip = value;
                this.ProperyChange("station_ip");
            }
        }


        public void ProperyChange(string name)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged.Invoke(this, new PropertyChangedEventArgs(name));
            }
        }

        #region INotifyPropertyChanged 成员

        public event PropertyChangedEventHandler PropertyChanged;

        #endregion
    }
}
