//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：oper_content_log_info
    /// </summary>
    public class OperContentLogInfo
    {
        
        /// <summary>
        /// 记录序号
        /// </summary>
        private decimal _content_sn;
        
        /// <summary>
        /// 线路id
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// 车站id
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// 项目名称
        /// </summary>
        private string _project_name;
        
        /// <summary>
        /// 内容说明
        /// </summary>
        private string _content;
        
        /// <summary>
        /// 操作员id
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// 更新日期
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// 更新时间
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// 记录序号
        /// </summary>
        public decimal content_sn
        {
            get
            {
                return this._content_sn;
            }
            set
            {
                this._content_sn = value;
            }
        }
        
        /// <summary>
        /// 线路id
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// 车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// 项目名称
        /// </summary>
        public string project_name
        {
            get
            {
                return this._project_name;
            }
            set
            {
                this._project_name = value;
            }
        }
        
        /// <summary>
        /// 内容说明
        /// </summary>
        public string content
        {
            get
            {
                return this._content;
            }
            set
            {
                this._content = value;
            }
        }
        
        /// <summary>
        /// 操作员id
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// 更新日期
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
