//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4043_tvm_tick_read
    /// </summary>
    public class Para4043TvmTickRead
    {
        
        /// <summary>
        /// COLUMN: TICK_ERROR_MAX_NUM
        /// </summary>
        private string _tick_error_max_num;
        
        /// <summary>
        /// COLUMN: UNFINISHED_CARD_WAIT_TIME
        /// </summary>
        private string _unfinished_card_wait_time;
        
        /// <summary>
        /// COLUMN: UNFINISHIED_RETRY_TIMES
        /// </summary>
        private string _unfinishied_retry_times;
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: TICK_ERROR_MAX_NUM
        /// </summary>
        public string tick_error_max_num
        {
            get
            {
                return this._tick_error_max_num;
            }
            set
            {
                this._tick_error_max_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UNFINISHED_CARD_WAIT_TIME
        /// </summary>
        public string unfinished_card_wait_time
        {
            get
            {
                return this._unfinished_card_wait_time;
            }
            set
            {
                this._unfinished_card_wait_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UNFINISHIED_RETRY_TIMES
        /// </summary>
        public string unfinishied_retry_times
        {
            get
            {
                return this._unfinishied_retry_times;
            }
            set
            {
                this._unfinishied_retry_times = value;
            }
        }
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
    }
}
