//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4037_adv_play
    /// </summary>
    public class Para4037AdvPlay
    {
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: ADV_DISPLAY_MODE
        /// </summary>
        private string _adv_display_mode;
        
        /// <summary>
        /// COLUMN: ADV_MODE_START_TIME
        /// </summary>
        private string _adv_mode_start_time;
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ADV_DISPLAY_MODE
        /// </summary>
        public string adv_display_mode
        {
            get
            {
                return this._adv_display_mode;
            }
            set
            {
                this._adv_display_mode = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ADV_MODE_START_TIME
        /// </summary>
        public string adv_mode_start_time
        {
            get
            {
                return this._adv_mode_start_time;
            }
            set
            {
                this._adv_mode_start_time = value;
            }
        }
    }
}
