//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4043_min_query_tran_amoun
    /// </summary>
    public class Para4043MinQueryTranAmoun
    {
        
        /// <summary>
        /// COLUMN: MIN_QUERY_TRAN_AMOUNT
        /// </summary>
        private string _min_query_tran_amount;
        
        /// <summary>
        /// COLUMN: MIN_QUERY_TRAN_TIME
        /// </summary>
        private string _min_query_tran_time;
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: MIN_QUERY_TRAN_AMOUNT
        /// </summary>
        public string min_query_tran_amount
        {
            get
            {
                return this._min_query_tran_amount;
            }
            set
            {
                this._min_query_tran_amount = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MIN_QUERY_TRAN_TIME
        /// </summary>
        public string min_query_tran_time
        {
            get
            {
                return this._min_query_tran_time;
            }
            set
            {
                this._min_query_tran_time = value;
            }
        }
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
    }
}
