//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace AFC.WS.UI.UIPage.CashManager {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataTvmSettlementSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataTvmSettlementSet : global::System.Data.DataSet {
        
        private TvmSettlementDataTable tableTvmSettlement;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataTvmSettlementSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataTvmSettlementSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TvmSettlement"] != null)) {
                    base.Tables.Add(new TvmSettlementDataTable(ds.Tables["TvmSettlement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TvmSettlementDataTable TvmSettlement {
            get {
                return this.tableTvmSettlement;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataTvmSettlementSet cln = ((DataTvmSettlementSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TvmSettlement"] != null)) {
                    base.Tables.Add(new TvmSettlementDataTable(ds.Tables["TvmSettlement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTvmSettlement = ((TvmSettlementDataTable)(base.Tables["TvmSettlement"]));
            if ((initTable == true)) {
                if ((this.tableTvmSettlement != null)) {
                    this.tableTvmSettlement.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataTvmSettlementSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataTvmSettlementSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTvmSettlement = new TvmSettlementDataTable();
            base.Tables.Add(this.tableTvmSettlement);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeTvmSettlement() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataTvmSettlementSet ds = new DataTvmSettlementSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void TvmSettlementRowChangeEventHandler(object sender, TvmSettlementRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TvmSettlementDataTable : global::System.Data.TypedTableBase<TvmSettlementRow> {
            
            private global::System.Data.DataColumn columnbusi_udsn;
            
            private global::System.Data.DataColumn columnstation_name;
            
            private global::System.Data.DataColumn columnoccur_date_time;
            
            private global::System.Data.DataColumn columnsail_num;
            
            private global::System.Data.DataColumn columnsail_sum;
            
            private global::System.Data.DataColumn columncharge_num;
            
            private global::System.Data.DataColumn columncharge_sum;
            
            private global::System.Data.DataColumn columntran_total_value;
            
            private global::System.Data.DataColumn columntotal_supply_ticket_num;
            
            private global::System.Data.DataColumn columntotal_recycle_ticket_num;
            
            private global::System.Data.DataColumn columnlast_ticket_remain_num;
            
            private global::System.Data.DataColumn columntoday_ticket_remain_num;
            
            private global::System.Data.DataColumn columnwaste_ticket_num;
            
            private global::System.Data.DataColumn columntotal_supply_bill_sum;
            
            private global::System.Data.DataColumn columntotal_recycle_bill_sum;
            
            private global::System.Data.DataColumn columntotal_encash_bill_sum;
            
            private global::System.Data.DataColumn columntotal_change_bill_sum;
            
            private global::System.Data.DataColumn columnlast_remain_bill_sum;
            
            private global::System.Data.DataColumn columntoday_remain_bill_sum;
            
            private global::System.Data.DataColumn columnbill_total_value;
            
            private global::System.Data.DataColumn columntotal_recycle_coin_sum;
            
            private global::System.Data.DataColumn columntotal_encash_coin_sum;
            
            private global::System.Data.DataColumn columnlast_remain_coin_sum;
            
            private global::System.Data.DataColumn columntoday_remain_coin_sum;
            
            private global::System.Data.DataColumn columnfault_trans_num;
            
            private global::System.Data.DataColumn columnfault_trans_sum;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementDataTable() {
                this.TableName = "TvmSettlement";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TvmSettlementDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected TvmSettlementDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn busi_udsnColumn {
                get {
                    return this.columnbusi_udsn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn station_nameColumn {
                get {
                    return this.columnstation_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn occur_date_timeColumn {
                get {
                    return this.columnoccur_date_time;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sail_numColumn {
                get {
                    return this.columnsail_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn sail_sumColumn {
                get {
                    return this.columnsail_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn charge_numColumn {
                get {
                    return this.columncharge_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn charge_sumColumn {
                get {
                    return this.columncharge_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn tran_total_valueColumn {
                get {
                    return this.columntran_total_value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_supply_ticket_numColumn {
                get {
                    return this.columntotal_supply_ticket_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_recycle_ticket_numColumn {
                get {
                    return this.columntotal_recycle_ticket_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn last_ticket_remain_numColumn {
                get {
                    return this.columnlast_ticket_remain_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn today_ticket_remain_numColumn {
                get {
                    return this.columntoday_ticket_remain_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn waste_ticket_numColumn {
                get {
                    return this.columnwaste_ticket_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_supply_bill_sumColumn {
                get {
                    return this.columntotal_supply_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_recycle_bill_sumColumn {
                get {
                    return this.columntotal_recycle_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_encash_bill_sumColumn {
                get {
                    return this.columntotal_encash_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_change_bill_sumColumn {
                get {
                    return this.columntotal_change_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn last_remain_bill_sumColumn {
                get {
                    return this.columnlast_remain_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn today_remain_bill_sumColumn {
                get {
                    return this.columntoday_remain_bill_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn bill_total_valueColumn {
                get {
                    return this.columnbill_total_value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_recycle_coin_sumColumn {
                get {
                    return this.columntotal_recycle_coin_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn total_encash_coin_sumColumn {
                get {
                    return this.columntotal_encash_coin_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn last_remain_coin_sumColumn {
                get {
                    return this.columnlast_remain_coin_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn today_remain_coin_sumColumn {
                get {
                    return this.columntoday_remain_coin_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fault_trans_numColumn {
                get {
                    return this.columnfault_trans_num;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn fault_trans_sumColumn {
                get {
                    return this.columnfault_trans_sum;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementRow this[int index] {
                get {
                    return ((TvmSettlementRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TvmSettlementRowChangeEventHandler TvmSettlementRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TvmSettlementRowChangeEventHandler TvmSettlementRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TvmSettlementRowChangeEventHandler TvmSettlementRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TvmSettlementRowChangeEventHandler TvmSettlementRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddTvmSettlementRow(TvmSettlementRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementRow AddTvmSettlementRow(
                        string busi_udsn, 
                        string station_name, 
                        string occur_date_time, 
                        string sail_num, 
                        string sail_sum, 
                        string charge_num, 
                        string charge_sum, 
                        string tran_total_value, 
                        string total_supply_ticket_num, 
                        string total_recycle_ticket_num, 
                        string last_ticket_remain_num, 
                        string today_ticket_remain_num, 
                        string waste_ticket_num, 
                        string total_supply_bill_sum, 
                        string total_recycle_bill_sum, 
                        string total_encash_bill_sum, 
                        string total_change_bill_sum, 
                        string last_remain_bill_sum, 
                        string today_remain_bill_sum, 
                        string bill_total_value, 
                        string total_recycle_coin_sum, 
                        string total_encash_coin_sum, 
                        string last_remain_coin_sum, 
                        string today_remain_coin_sum, 
                        string fault_trans_num, 
                        string fault_trans_sum) {
                TvmSettlementRow rowTvmSettlementRow = ((TvmSettlementRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        busi_udsn,
                        station_name,
                        occur_date_time,
                        sail_num,
                        sail_sum,
                        charge_num,
                        charge_sum,
                        tran_total_value,
                        total_supply_ticket_num,
                        total_recycle_ticket_num,
                        last_ticket_remain_num,
                        today_ticket_remain_num,
                        waste_ticket_num,
                        total_supply_bill_sum,
                        total_recycle_bill_sum,
                        total_encash_bill_sum,
                        total_change_bill_sum,
                        last_remain_bill_sum,
                        today_remain_bill_sum,
                        bill_total_value,
                        total_recycle_coin_sum,
                        total_encash_coin_sum,
                        last_remain_coin_sum,
                        today_remain_coin_sum,
                        fault_trans_num,
                        fault_trans_sum};
                rowTvmSettlementRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTvmSettlementRow);
                return rowTvmSettlementRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TvmSettlementDataTable cln = ((TvmSettlementDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TvmSettlementDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnbusi_udsn = base.Columns["busi_udsn"];
                this.columnstation_name = base.Columns["station_name"];
                this.columnoccur_date_time = base.Columns["occur_date_time"];
                this.columnsail_num = base.Columns["sail_num"];
                this.columnsail_sum = base.Columns["sail_sum"];
                this.columncharge_num = base.Columns["charge_num"];
                this.columncharge_sum = base.Columns["charge_sum"];
                this.columntran_total_value = base.Columns["tran_total_value"];
                this.columntotal_supply_ticket_num = base.Columns["total_supply_ticket_num"];
                this.columntotal_recycle_ticket_num = base.Columns["total_recycle_ticket_num"];
                this.columnlast_ticket_remain_num = base.Columns["last_ticket_remain_num"];
                this.columntoday_ticket_remain_num = base.Columns["today_ticket_remain_num"];
                this.columnwaste_ticket_num = base.Columns["waste_ticket_num"];
                this.columntotal_supply_bill_sum = base.Columns["total_supply_bill_sum"];
                this.columntotal_recycle_bill_sum = base.Columns["total_recycle_bill_sum"];
                this.columntotal_encash_bill_sum = base.Columns["total_encash_bill_sum"];
                this.columntotal_change_bill_sum = base.Columns["total_change_bill_sum"];
                this.columnlast_remain_bill_sum = base.Columns["last_remain_bill_sum"];
                this.columntoday_remain_bill_sum = base.Columns["today_remain_bill_sum"];
                this.columnbill_total_value = base.Columns["bill_total_value"];
                this.columntotal_recycle_coin_sum = base.Columns["total_recycle_coin_sum"];
                this.columntotal_encash_coin_sum = base.Columns["total_encash_coin_sum"];
                this.columnlast_remain_coin_sum = base.Columns["last_remain_coin_sum"];
                this.columntoday_remain_coin_sum = base.Columns["today_remain_coin_sum"];
                this.columnfault_trans_num = base.Columns["fault_trans_num"];
                this.columnfault_trans_sum = base.Columns["fault_trans_sum"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnbusi_udsn = new global::System.Data.DataColumn("busi_udsn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbusi_udsn);
                this.columnstation_name = new global::System.Data.DataColumn("station_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstation_name);
                this.columnoccur_date_time = new global::System.Data.DataColumn("occur_date_time", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnoccur_date_time);
                this.columnsail_num = new global::System.Data.DataColumn("sail_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsail_num);
                this.columnsail_sum = new global::System.Data.DataColumn("sail_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsail_sum);
                this.columncharge_num = new global::System.Data.DataColumn("charge_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncharge_num);
                this.columncharge_sum = new global::System.Data.DataColumn("charge_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncharge_sum);
                this.columntran_total_value = new global::System.Data.DataColumn("tran_total_value", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntran_total_value);
                this.columntotal_supply_ticket_num = new global::System.Data.DataColumn("total_supply_ticket_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_supply_ticket_num);
                this.columntotal_recycle_ticket_num = new global::System.Data.DataColumn("total_recycle_ticket_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_recycle_ticket_num);
                this.columnlast_ticket_remain_num = new global::System.Data.DataColumn("last_ticket_remain_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_ticket_remain_num);
                this.columntoday_ticket_remain_num = new global::System.Data.DataColumn("today_ticket_remain_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntoday_ticket_remain_num);
                this.columnwaste_ticket_num = new global::System.Data.DataColumn("waste_ticket_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnwaste_ticket_num);
                this.columntotal_supply_bill_sum = new global::System.Data.DataColumn("total_supply_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_supply_bill_sum);
                this.columntotal_recycle_bill_sum = new global::System.Data.DataColumn("total_recycle_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_recycle_bill_sum);
                this.columntotal_encash_bill_sum = new global::System.Data.DataColumn("total_encash_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_encash_bill_sum);
                this.columntotal_change_bill_sum = new global::System.Data.DataColumn("total_change_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_change_bill_sum);
                this.columnlast_remain_bill_sum = new global::System.Data.DataColumn("last_remain_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_remain_bill_sum);
                this.columntoday_remain_bill_sum = new global::System.Data.DataColumn("today_remain_bill_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntoday_remain_bill_sum);
                this.columnbill_total_value = new global::System.Data.DataColumn("bill_total_value", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbill_total_value);
                this.columntotal_recycle_coin_sum = new global::System.Data.DataColumn("total_recycle_coin_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_recycle_coin_sum);
                this.columntotal_encash_coin_sum = new global::System.Data.DataColumn("total_encash_coin_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal_encash_coin_sum);
                this.columnlast_remain_coin_sum = new global::System.Data.DataColumn("last_remain_coin_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_remain_coin_sum);
                this.columntoday_remain_coin_sum = new global::System.Data.DataColumn("today_remain_coin_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntoday_remain_coin_sum);
                this.columnfault_trans_num = new global::System.Data.DataColumn("fault_trans_num", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfault_trans_num);
                this.columnfault_trans_sum = new global::System.Data.DataColumn("fault_trans_sum", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfault_trans_sum);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementRow NewTvmSettlementRow() {
                return ((TvmSettlementRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TvmSettlementRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TvmSettlementRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TvmSettlementRowChanged != null)) {
                    this.TvmSettlementRowChanged(this, new TvmSettlementRowChangeEvent(((TvmSettlementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TvmSettlementRowChanging != null)) {
                    this.TvmSettlementRowChanging(this, new TvmSettlementRowChangeEvent(((TvmSettlementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TvmSettlementRowDeleted != null)) {
                    this.TvmSettlementRowDeleted(this, new TvmSettlementRowChangeEvent(((TvmSettlementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TvmSettlementRowDeleting != null)) {
                    this.TvmSettlementRowDeleting(this, new TvmSettlementRowChangeEvent(((TvmSettlementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveTvmSettlementRow(TvmSettlementRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataTvmSettlementSet ds = new DataTvmSettlementSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TvmSettlementDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TvmSettlementRow : global::System.Data.DataRow {
            
            private TvmSettlementDataTable tableTvmSettlement;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TvmSettlementRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTvmSettlement = ((TvmSettlementDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string busi_udsn {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.busi_udsnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“busi_udsn”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.busi_udsnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string station_name {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.station_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“station_name”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.station_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string occur_date_time {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.occur_date_timeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“occur_date_time”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.occur_date_timeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sail_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.sail_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“sail_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.sail_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string sail_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.sail_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“sail_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.sail_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string charge_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.charge_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“charge_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.charge_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string charge_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.charge_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“charge_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.charge_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string tran_total_value {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.tran_total_valueColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“tran_total_value”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.tran_total_valueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_supply_ticket_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_supply_ticket_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_supply_ticket_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_supply_ticket_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_recycle_ticket_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_recycle_ticket_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_recycle_ticket_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_recycle_ticket_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string last_ticket_remain_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.last_ticket_remain_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“last_ticket_remain_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.last_ticket_remain_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string today_ticket_remain_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.today_ticket_remain_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“today_ticket_remain_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.today_ticket_remain_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string waste_ticket_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.waste_ticket_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“waste_ticket_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.waste_ticket_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_supply_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_supply_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_supply_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_supply_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_recycle_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_recycle_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_recycle_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_recycle_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_encash_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_encash_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_encash_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_encash_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_change_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_change_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_change_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_change_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string last_remain_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.last_remain_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“last_remain_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.last_remain_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string today_remain_bill_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.today_remain_bill_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“today_remain_bill_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.today_remain_bill_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string bill_total_value {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.bill_total_valueColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“bill_total_value”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.bill_total_valueColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_recycle_coin_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_recycle_coin_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_recycle_coin_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_recycle_coin_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string total_encash_coin_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.total_encash_coin_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“total_encash_coin_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.total_encash_coin_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string last_remain_coin_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.last_remain_coin_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“last_remain_coin_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.last_remain_coin_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string today_remain_coin_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.today_remain_coin_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“today_remain_coin_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.today_remain_coin_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fault_trans_num {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.fault_trans_numColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“fault_trans_num”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.fault_trans_numColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string fault_trans_sum {
                get {
                    try {
                        return ((string)(this[this.tableTvmSettlement.fault_trans_sumColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“TvmSettlement”中列“fault_trans_sum”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableTvmSettlement.fault_trans_sumColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isbusi_udsnNull() {
                return this.IsNull(this.tableTvmSettlement.busi_udsnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setbusi_udsnNull() {
                this[this.tableTvmSettlement.busi_udsnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isstation_nameNull() {
                return this.IsNull(this.tableTvmSettlement.station_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setstation_nameNull() {
                this[this.tableTvmSettlement.station_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isoccur_date_timeNull() {
                return this.IsNull(this.tableTvmSettlement.occur_date_timeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setoccur_date_timeNull() {
                this[this.tableTvmSettlement.occur_date_timeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issail_numNull() {
                return this.IsNull(this.tableTvmSettlement.sail_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsail_numNull() {
                this[this.tableTvmSettlement.sail_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Issail_sumNull() {
                return this.IsNull(this.tableTvmSettlement.sail_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setsail_sumNull() {
                this[this.tableTvmSettlement.sail_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ischarge_numNull() {
                return this.IsNull(this.tableTvmSettlement.charge_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcharge_numNull() {
                this[this.tableTvmSettlement.charge_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Ischarge_sumNull() {
                return this.IsNull(this.tableTvmSettlement.charge_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setcharge_sumNull() {
                this[this.tableTvmSettlement.charge_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istran_total_valueNull() {
                return this.IsNull(this.tableTvmSettlement.tran_total_valueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settran_total_valueNull() {
                this[this.tableTvmSettlement.tran_total_valueColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_supply_ticket_numNull() {
                return this.IsNull(this.tableTvmSettlement.total_supply_ticket_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_supply_ticket_numNull() {
                this[this.tableTvmSettlement.total_supply_ticket_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_recycle_ticket_numNull() {
                return this.IsNull(this.tableTvmSettlement.total_recycle_ticket_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_recycle_ticket_numNull() {
                this[this.tableTvmSettlement.total_recycle_ticket_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Islast_ticket_remain_numNull() {
                return this.IsNull(this.tableTvmSettlement.last_ticket_remain_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setlast_ticket_remain_numNull() {
                this[this.tableTvmSettlement.last_ticket_remain_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istoday_ticket_remain_numNull() {
                return this.IsNull(this.tableTvmSettlement.today_ticket_remain_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settoday_ticket_remain_numNull() {
                this[this.tableTvmSettlement.today_ticket_remain_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Iswaste_ticket_numNull() {
                return this.IsNull(this.tableTvmSettlement.waste_ticket_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setwaste_ticket_numNull() {
                this[this.tableTvmSettlement.waste_ticket_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_supply_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_supply_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_supply_bill_sumNull() {
                this[this.tableTvmSettlement.total_supply_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_recycle_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_recycle_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_recycle_bill_sumNull() {
                this[this.tableTvmSettlement.total_recycle_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_encash_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_encash_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_encash_bill_sumNull() {
                this[this.tableTvmSettlement.total_encash_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_change_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_change_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_change_bill_sumNull() {
                this[this.tableTvmSettlement.total_change_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Islast_remain_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.last_remain_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setlast_remain_bill_sumNull() {
                this[this.tableTvmSettlement.last_remain_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istoday_remain_bill_sumNull() {
                return this.IsNull(this.tableTvmSettlement.today_remain_bill_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settoday_remain_bill_sumNull() {
                this[this.tableTvmSettlement.today_remain_bill_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isbill_total_valueNull() {
                return this.IsNull(this.tableTvmSettlement.bill_total_valueColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setbill_total_valueNull() {
                this[this.tableTvmSettlement.bill_total_valueColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_recycle_coin_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_recycle_coin_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_recycle_coin_sumNull() {
                this[this.tableTvmSettlement.total_recycle_coin_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istotal_encash_coin_sumNull() {
                return this.IsNull(this.tableTvmSettlement.total_encash_coin_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settotal_encash_coin_sumNull() {
                this[this.tableTvmSettlement.total_encash_coin_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Islast_remain_coin_sumNull() {
                return this.IsNull(this.tableTvmSettlement.last_remain_coin_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setlast_remain_coin_sumNull() {
                this[this.tableTvmSettlement.last_remain_coin_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Istoday_remain_coin_sumNull() {
                return this.IsNull(this.tableTvmSettlement.today_remain_coin_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Settoday_remain_coin_sumNull() {
                this[this.tableTvmSettlement.today_remain_coin_sumColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfault_trans_numNull() {
                return this.IsNull(this.tableTvmSettlement.fault_trans_numColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfault_trans_numNull() {
                this[this.tableTvmSettlement.fault_trans_numColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isfault_trans_sumNull() {
                return this.IsNull(this.tableTvmSettlement.fault_trans_sumColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setfault_trans_sumNull() {
                this[this.tableTvmSettlement.fault_trans_sumColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class TvmSettlementRowChangeEvent : global::System.EventArgs {
            
            private TvmSettlementRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementRowChangeEvent(TvmSettlementRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TvmSettlementRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591