//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;


    /// <summary>
    /// 数据库表名称：basi_dev_info
    /// </summary>
    public class BasiDevInfo
    {

        /// <summary>
        /// 设备id
        /// </summary>
        private string _device_id;

        /// <summary>
        /// COLUMN: DEVICE_CODE
        /// </summary>
        private decimal _device_code;

        /// <summary>
        /// 设备类型
        /// </summary>
        private string _device_type;

        /// <summary>
        /// 设备子类型
        /// </summary>
        private string _device_sub_type;

        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        private string _line_id;

        /// <summary>
        /// COLUMN: STATION_AREA_ID
        /// </summary>
        private string _station_area_id;

        /// <summary>
        /// 车站id
        /// </summary>
        private string _station_id;

        /// <summary>
        /// 设备所属站厅
        /// </summary>
        private string _station_hall_id;

        /// <summary>
        /// COLUMN: HALL_GROUP_ID
        /// </summary>
        private string _hall_group_id;

        /// <summary>
        /// ip的4个字节以u32_t从高位到低位表示
        /// </summary>
        private string _device_ip;

        /// <summary>
        /// COLUMN: MAC_IP
        /// </summary>
        private string _mac_ip;

        /// <summary>
        /// 设备管理状态：0x01：在用；0x02：停用；0x03：移除
        /// </summary>
        private string _devi_use_status;

        /// <summary>
        /// COLUMN: REMARK_256
        /// </summary>
        private string _remark_256;

        /// <summary>
        /// 1:lc;2:sc;3:dss
        /// </summary>
        private string _location_type;

        /// <summary>
        /// 设备序号
        /// </summary>
        private decimal _device_serial_no;

        /// <summary>
        /// 设备组内序号
        /// </summary>
        private string _group_serial_no;

        /// <summary>
        /// 设备名称
        /// </summary>
        private string _device_name;

        /// <summary>
        /// 单位：像素，设备图标原点与监视区域原点的横向距离
        ///
        /// </summary>
        private decimal _honri_rela_distance;

        /// <summary>
        /// 单位：像素，设备图标原点与监视区域原点的纵向距离
        ///
        /// </summary>
        private decimal _verti_rela_distance;

        /// <summary>
        /// 1-上；2-右上；3-右；4-右下；5-下；6-左下；7-左；8-左上v
        /// </summary>
        private string _device_direction;

        /// <summary>
        /// 设备id
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }

        /// <summary>
        /// COLUMN: DEVICE_CODE
        /// </summary>
        public decimal device_code
        {
            get
            {
                return this._device_code;
            }
            set
            {
                this._device_code = value;
            }
        }

        /// <summary>
        /// 设备类型
        /// </summary>
        public string device_type
        {
            get
            {
                return this._device_type;
            }
            set
            {
                this._device_type = value;
            }
        }

        /// <summary>
        /// 设备子类型
        /// </summary>
        public string device_sub_type
        {
            get
            {
                return this._device_sub_type;
            }
            set
            {
                this._device_sub_type = value;
            }
        }

        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }

        /// <summary>
        /// COLUMN: STATION_AREA_ID
        /// </summary>
        public string station_area_id
        {
            get
            {
                return this._station_area_id;
            }
            set
            {
                this._station_area_id = value;
            }
        }

        /// <summary>
        /// 车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }

        /// <summary>
        /// 设备所属站厅
        /// </summary>
        public string station_hall_id
        {
            get
            {
                return this._station_hall_id;
            }
            set
            {
                this._station_hall_id = value;
            }
        }

        /// <summary>
        /// COLUMN: HALL_GROUP_ID
        /// </summary>
        public string hall_group_id
        {
            get
            {
                return this._hall_group_id;
            }
            set
            {
                this._hall_group_id = value;
            }
        }

        /// <summary>
        /// ip的4个字节以u32_t从高位到低位表示
        /// </summary>
        public string device_ip
        {
            get
            {
                return this._device_ip;
            }
            set
            {
                this._device_ip = value;
            }
        }

        /// <summary>
        /// COLUMN: MAC_IP
        /// </summary>
        public string mac_ip
        {
            get
            {
                return this._mac_ip;
            }
            set
            {
                this._mac_ip = value;
            }
        }

        /// <summary>
        /// 设备管理状态：0x01：在用；0x02：停用；0x03：移除
        /// </summary>
        public string devi_use_status
        {
            get
            {
                return this._devi_use_status;
            }
            set
            {
                this._devi_use_status = value;
            }
        }

        /// <summary>
        /// COLUMN: REMARK_256
        /// </summary>
        public string remark_256
        {
            get
            {
                return this._remark_256;
            }
            set
            {
                this._remark_256 = value;
            }
        }

        /// <summary>
        /// 1:lc;2:sc;3:dss
        /// </summary>
        public string location_type
        {
            get
            {
                return this._location_type;
            }
            set
            {
                this._location_type = value;
            }
        }

        /// <summary>
        /// 设备序号
        /// </summary>
        public decimal device_serial_no
        {
            get
            {
                return this._device_serial_no;
            }
            set
            {
                this._device_serial_no = value;
            }
        }

        /// <summary>
        /// 设备组内序号
        /// </summary>
        public string group_serial_no
        {
            get
            {
                return this._group_serial_no;
            }
            set
            {
                this._group_serial_no = value;
            }
        }

        /// <summary>
        /// 设备名称
        /// </summary>
        public string device_name
        {
            get
            {
                return this._device_name;
            }
            set
            {
                this._device_name = value;
            }
        }

        /// <summary>
        /// 单位：像素，设备图标原点与监视区域原点的横向距离
        ///
        /// </summary>
        public decimal honri_rela_distance
        {
            get
            {
                return this._honri_rela_distance;
            }
            set
            {
                this._honri_rela_distance = value;
            }
        }

        /// <summary>
        /// 单位：像素，设备图标原点与监视区域原点的纵向距离
        ///
        /// </summary>
        public decimal verti_rela_distance
        {
            get
            {
                return this._verti_rela_distance;
            }
            set
            {
                this._verti_rela_distance = value;
            }
        }

        /// <summary>
        /// 1-上；2-右上；3-右；4-右下；5-下；6-左下；7-左；8-左上v
        /// </summary>
        public string device_direction
        {
            get
            {
                return this._device_direction;
            }
            set
            {
                this._device_direction = value;
            }
        }
    }
}
