//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_tran_type_info
    /// </summary>
    public class BasiTranTypeInfo
    {
        
        /// <summary>
        /// COLUMN: TRAN_TYPE
        /// </summary>
        private string _tran_type;
        
        /// <summary>
        /// COLUMN: TRAN_SUB_TYPE
        /// </summary>
        private string _tran_sub_type;
        
        /// <summary>
        /// COLUMN: TRAN_NAME
        /// </summary>
        private string _tran_name;
        
        /// <summary>
        /// COLUMN: AFC_TYPE
        /// </summary>
        private string _afc_type;
        
        /// <summary>
        /// COLUMN: AFC_NAME
        /// </summary>
        private string _afc_name;
        
        /// <summary>
        /// COLUMN: TRAN_TYPE
        /// </summary>
        public string tran_type
        {
            get
            {
                return this._tran_type;
            }
            set
            {
                this._tran_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TRAN_SUB_TYPE
        /// </summary>
        public string tran_sub_type
        {
            get
            {
                return this._tran_sub_type;
            }
            set
            {
                this._tran_sub_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TRAN_NAME
        /// </summary>
        public string tran_name
        {
            get
            {
                return this._tran_name;
            }
            set
            {
                this._tran_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AFC_TYPE
        /// </summary>
        public string afc_type
        {
            get
            {
                return this._afc_type;
            }
            set
            {
                this._afc_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AFC_NAME
        /// </summary>
        public string afc_name
        {
            get
            {
                return this._afc_name;
            }
            set
            {
                this._afc_name = value;
            }
        }
    }
}
