//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_tick_mana_type_info
    /// </summary>
    public class BasiTickManaTypeInfo
    {
        
        /// <summary>
        /// 库存管理类型
        /// </summary>
        private string _tick_mana_type;
        
        /// <summary>
        /// 库存管理类型名称
        /// </summary>
        private string _tick_mana_type_name;
        
        /// <summary>
        /// 票卡物理类型
        /// </summary>
        private string _ticket_phy_type;
        
        /// <summary>
        /// 票卡物理类型中文名称
        /// </summary>
        private string _ticket_phy_type_name;
        
        /// <summary>
        /// 票种基本类型（大类分类）
        /// </summary>
        private string _ticket_family_type;
        
        /// <summary>
        /// 票种类型中文名称
        /// </summary>
        private string _ticket_family_type_name;
        
        /// <summary>
        /// 票卡发行商id
        /// </summary>
        private string _card_issue_id;
        
        /// <summary>
        /// 库存管理类型
        /// </summary>
        public string tick_mana_type
        {
            get
            {
                return this._tick_mana_type;
            }
            set
            {
                this._tick_mana_type = value;
            }
        }
        
        /// <summary>
        /// 库存管理类型名称
        /// </summary>
        public string tick_mana_type_name
        {
            get
            {
                return this._tick_mana_type_name;
            }
            set
            {
                this._tick_mana_type_name = value;
            }
        }
        
        /// <summary>
        /// 票卡物理类型
        /// </summary>
        public string ticket_phy_type
        {
            get
            {
                return this._ticket_phy_type;
            }
            set
            {
                this._ticket_phy_type = value;
            }
        }
        
        /// <summary>
        /// 票卡物理类型中文名称
        /// </summary>
        public string ticket_phy_type_name
        {
            get
            {
                return this._ticket_phy_type_name;
            }
            set
            {
                this._ticket_phy_type_name = value;
            }
        }
        
        /// <summary>
        /// 票种基本类型（大类分类）
        /// </summary>
        public string ticket_family_type
        {
            get
            {
                return this._ticket_family_type;
            }
            set
            {
                this._ticket_family_type = value;
            }
        }
        
        /// <summary>
        /// 票种类型中文名称
        /// </summary>
        public string ticket_family_type_name
        {
            get
            {
                return this._ticket_family_type_name;
            }
            set
            {
                this._ticket_family_type_name = value;
            }
        }
        
        /// <summary>
        /// 票卡发行商id
        /// </summary>
        public string card_issue_id
        {
            get
            {
                return this._card_issue_id;
            }
            set
            {
                this._card_issue_id = value;
            }
        }
    }
}
