//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：dev_status_alarm_cfg
    /// </summary>
    public class DevStatusAlarmHistory
    {
        
        /// <summary>
        ///
        /// </summary>
        private string _line_id;
        
        /// <summary>
        ///
        /// </summary>
        private string _station_id;
        
        /// <summary>
        ///
        /// </summary>
        private string _device_id;

        /// <summary>
        ///
        /// </summary>
        private string _status_id;

        /// <summary>
        ///
        /// </summary>
        private string _status_value;

        /// <summary>
        ///
        /// </summary>
        private string _is_normal;

        /// <summary>
        ///
        /// </summary>
        private string _normal_date;

        /// <summary>
        ///
        /// </summary>
        private string _normal_time;

        /// <summary>
        ///
        /// </summary>
        private string _is_confirm;

        /// <summary>
        ///
        /// </summary>
        private string _confirm_date;

        /// <summary>
        ///
        /// </summary>
        private string _confirm_time;

        /// <summary>
        ///
        /// </summary>
        private string _confirm_oper;

        /// <summary>
        ///
        /// </summary>
        private string _update_date;

        /// <summary>
        ///
        /// </summary>
        private string _update_time;

        /// <summary>
        /// 
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string status_id
        {
            get
            {
                return this._status_id;
            }
            set
            {
                this._status_id = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string status_value
        {
            get
            {
                return this._status_value;
            }
            set
            {
                this._status_value = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string is_normal
        {
            get
            {
                return this._is_normal;
            }
            set
            {
                this._is_normal = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string normal_date
        {
            get
            {
                return this._normal_date;
            }
            set
            {
                this._normal_date = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string normal_time
        {
            get
            {
                return this._normal_time;
            }
            set
            {
                this._normal_time = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string is_confirm
        {
            get
            {
                return this._is_confirm;
            }
            set
            {
                this._is_confirm = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string confirm_date
        {
            get
            {
                return this._confirm_date;
            }
            set
            {
                this._confirm_date = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string confirm_time
        {
            get
            {
                return this._confirm_time;
            }
            set
            {
                this._confirm_time = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string confirm_oper
        {
            get
            {
                return this._confirm_oper;
            }
            set
            {
                this._confirm_oper = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }

        /// <summary>
        ///
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
