//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4037_suspend_status
    /// </summary>
    public class Para4037SuspendStatus
    {
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_FILE_NAME
        /// </summary>
        private string _suspend_window_file_name;
        
        /// <summary>
        /// COLUMN: LEFT_UP_X_INDEX
        /// </summary>
        private string _left_up_x_index;
        
        /// <summary>
        /// COLUMN: LEFT_UP_Y_INDEX
        /// </summary>
        private string _left_up_y_index;
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_WIDE
        /// </summary>
        private string _suspend_window_wide;
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_HIGH
        /// </summary>
        private string _suspend_window_high;
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_FILE_NAME
        /// </summary>
        public string suspend_window_file_name
        {
            get
            {
                return this._suspend_window_file_name;
            }
            set
            {
                this._suspend_window_file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LEFT_UP_X_INDEX
        /// </summary>
        public string left_up_x_index
        {
            get
            {
                return this._left_up_x_index;
            }
            set
            {
                this._left_up_x_index = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LEFT_UP_Y_INDEX
        /// </summary>
        public string left_up_y_index
        {
            get
            {
                return this._left_up_y_index;
            }
            set
            {
                this._left_up_y_index = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_WIDE
        /// </summary>
        public string suspend_window_wide
        {
            get
            {
                return this._suspend_window_wide;
            }
            set
            {
                this._suspend_window_wide = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SUSPEND_WINDOW_HIGH
        /// </summary>
        public string suspend_window_high
        {
            get
            {
                return this._suspend_window_high;
            }
            set
            {
                this._suspend_window_high = value;
            }
        }
    }
}
