//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4037_fare_value_selection
    /// </summary>
    public class Para4037FareValueSelection
    {
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: FARE_VALUE_SELECTION_ID
        /// </summary>
        private string _fare_value_selection_id;
        
        /// <summary>
        /// COLUMN: FARE_DISPLAY_VALUE
        /// </summary>
        private string _fare_display_value;
        
        /// <summary>
        /// COLUMN: FARE_GROUP_LEVEL
        /// </summary>
        private string _fare_group_level;
        
        /// <summary>
        /// COLUMN: FARE_LEFT_UP_X_INDEX
        /// </summary>
        private string _fare_left_up_x_index;
        
        /// <summary>
        /// COLUMN: FARE_LEFT_UP_Y_VALUE
        /// </summary>
        private string _fare_left_up_y_value;
        
        /// <summary>
        /// COLUMN: FARE_BUTTON_WIDE
        /// </summary>
        private string _fare_button_wide;
        
        /// <summary>
        /// COLUMN: FARE_BUTTON_HIGH
        /// </summary>
        private string _fare_button_high;
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_VALUE_SELECTION_ID
        /// </summary>
        public string fare_value_selection_id
        {
            get
            {
                return this._fare_value_selection_id;
            }
            set
            {
                this._fare_value_selection_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_DISPLAY_VALUE
        /// </summary>
        public string fare_display_value
        {
            get
            {
                return this._fare_display_value;
            }
            set
            {
                this._fare_display_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_GROUP_LEVEL
        /// </summary>
        public string fare_group_level
        {
            get
            {
                return this._fare_group_level;
            }
            set
            {
                this._fare_group_level = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_LEFT_UP_X_INDEX
        /// </summary>
        public string fare_left_up_x_index
        {
            get
            {
                return this._fare_left_up_x_index;
            }
            set
            {
                this._fare_left_up_x_index = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_LEFT_UP_Y_VALUE
        /// </summary>
        public string fare_left_up_y_value
        {
            get
            {
                return this._fare_left_up_y_value;
            }
            set
            {
                this._fare_left_up_y_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_BUTTON_WIDE
        /// </summary>
        public string fare_button_wide
        {
            get
            {
                return this._fare_button_wide;
            }
            set
            {
                this._fare_button_wide = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FARE_BUTTON_HIGH
        /// </summary>
        public string fare_button_high
        {
            get
            {
                return this._fare_button_high;
            }
            set
            {
                this._fare_button_high = value;
            }
        }
    }
}
