//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_4021_run_mode_record
    /// </summary>
    public class Para4021RunModeRecord
    {
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        private decimal _mode_code;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        private decimal _line_id;
        
        /// <summary>
        /// 车站id
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: DEGRADE_MODE_HAPPEN_TIME
        /// </summary>
        private string _degrade_mode_happen_time;
        
        /// <summary>
        /// COLUMN: DEGRADE_MODE_END_TIME
        /// </summary>
        private string _degrade_mode_end_time;
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        public decimal mode_code
        {
            get
            {
                return this._mode_code;
            }
            set
            {
                this._mode_code = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        public decimal line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// 车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEGRADE_MODE_HAPPEN_TIME
        /// </summary>
        public string degrade_mode_happen_time
        {
            get
            {
                return this._degrade_mode_happen_time;
            }
            set
            {
                this._degrade_mode_happen_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEGRADE_MODE_END_TIME
        /// </summary>
        public string degrade_mode_end_time
        {
            get
            {
                return this._degrade_mode_end_time;
            }
            set
            {
                this._degrade_mode_end_time = value;
            }
        }
    }
}
