//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_version_info
    /// </summary>
    public class ParaVersionInfo
    {
        
        /// <summary>
        /// 参数类型
        /// </summary>
        private string _para_type;
        
        /// <summary>
        /// 参数子类型
        /// </summary>
        private string _para_sub_type;
        
        /// <summary>
        /// 主控文件类型
        /// </summary>
        private string _para_master_type;
        
        /// <summary>
        /// 主控版本号
        /// </summary>
        private string _master_para_version;
        
        /// <summary>
        /// 版本号
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// 参数名称
        /// </summary>
        private string _para_file_name;
        
        /// <summary>
        /// 生成日期
        /// </summary>
        private string _occur_date;
        
        /// <summary>
        /// 参数生成时间
        /// </summary>
        private string _occur_time;
        
        /// <summary>
        /// 生效日期
        /// </summary>
        private string _active_date;
        
        /// <summary>
        /// COLUMN: ACTIVE_TIME
        /// </summary>
        private string _active_time;
        
        /// <summary>
        /// 更新日期
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// 更新时间
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// 参数类型
        /// </summary>
        public string para_type
        {
            get
            {
                return this._para_type;
            }
            set
            {
                this._para_type = value;
            }
        }
        
        /// <summary>
        /// 参数子类型
        /// </summary>
        public string para_sub_type
        {
            get
            {
                return this._para_sub_type;
            }
            set
            {
                this._para_sub_type = value;
            }
        }
        
        /// <summary>
        /// 主控文件类型
        /// </summary>
        public string para_master_type
        {
            get
            {
                return this._para_master_type;
            }
            set
            {
                this._para_master_type = value;
            }
        }
        
        /// <summary>
        /// 主控版本号
        /// </summary>
        public string master_para_version
        {
            get
            {
                return this._master_para_version;
            }
            set
            {
                this._master_para_version = value;
            }
        }
        
        /// <summary>
        /// 版本号
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// 参数名称
        /// </summary>
        public string para_file_name
        {
            get
            {
                return this._para_file_name;
            }
            set
            {
                this._para_file_name = value;
            }
        }
        
        /// <summary>
        /// 生成日期
        /// </summary>
        public string occur_date
        {
            get
            {
                return this._occur_date;
            }
            set
            {
                this._occur_date = value;
            }
        }
        
        /// <summary>
        /// 参数生成时间
        /// </summary>
        public string occur_time
        {
            get
            {
                return this._occur_time;
            }
            set
            {
                this._occur_time = value;
            }
        }
        
        /// <summary>
        /// 生效日期
        /// </summary>
        public string active_date
        {
            get
            {
                return this._active_date;
            }
            set
            {
                this._active_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACTIVE_TIME
        /// </summary>
        public string active_time
        {
            get
            {
                return this._active_time;
            }
            set
            {
                this._active_time = value;
            }
        }
        
        /// <summary>
        /// 更新日期
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
