//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：tick_operator_return_log
    /// </summary>
    public class TickOperatorReturnLog
    {
        
        /// <summary>
        /// 记录主键
        /// </summary>
        private decimal _oper_sec;
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// 当表示lc的库存时，本字段为lc的车站id
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// 操作员id
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// 00：领用  01：归还
        /// </summary>
        private string _operate_type;
        
        /// <summary>
        /// 库存管理类型
        /// </summary>
        private string _tick_mana_type;
        
        /// <summary>
        /// COLUMN: TICKET_NUM
        /// </summary>
        private decimal _ticket_num;
        
        /// <summary>
        /// 更新日期
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// 更新时间
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// 记录主键
        /// </summary>
        public decimal oper_sec
        {
            get
            {
                return this._oper_sec;
            }
            set
            {
                this._oper_sec = value;
            }
        }
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// 当表示lc的库存时，本字段为lc的车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// 操作员id
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// 00：领用  01：归还
        /// </summary>
        public string operate_type
        {
            get
            {
                return this._operate_type;
            }
            set
            {
                this._operate_type = value;
            }
        }
        
        /// <summary>
        /// 库存管理类型
        /// </summary>
        public string tick_mana_type
        {
            get
            {
                return this._tick_mana_type;
            }
            set
            {
                this._tick_mana_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICKET_NUM
        /// </summary>
        public decimal ticket_num
        {
            get
            {
                return this._ticket_num;
            }
            set
            {
                this._ticket_num = value;
            }
        }
        
        /// <summary>
        /// 更新日期
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
