//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_para_type_info
    /// </summary>
    public class BasiParaTypeInfo
    {
        
        /// <summary>
        /// 参数类型
        /// </summary>
        private string _para_type;
        
        /// <summary>
        /// 参数子类型
        /// </summary>
        private string _para_sub_type;
        
        /// <summary>
        /// 全路径名称
        /// </summary>
        private string _para_file_name;
        
        /// <summary>
        /// 使用4个字节（32位）位图描述，每一位表示一种设备类型，置1表示为该类设备使用，置0表示不使用。
        ///bit00：服务器
        ///bit01：工作站
        ///bit02：网络设备
        ///bit03：ups
        ///bit04：e/s
        ///bit05：agm
        ///bit06：bom
        ///bit07：tvm
        ///bit08：avm
        ///bit09：tcm
        ///bit10：pca
        ///bit11~bit31：预留
        ///
        /// </summary>
        private string _user_type_bit_map;
        
        /// <summary>
        /// 1：acc
        ///2:  lcc
        ///
        /// </summary>
        private string _para_source;
        
        /// <summary>
        /// 1：即时生效，0：不即时生效
        /// </summary>
        private string _is_instant_active;
        
        /// <summary>
        /// 1：即时参数，0：非即时参数
        /// </summary>
        private string _is_instant_para;
        
        /// <summary>
        /// 描述参数的作用
        /// </summary>
        private string _para_desc;
        
        /// <summary>
        /// 1：为本系统使用该参数，0：为本系统不使用该参数。
        ///注：主要用于服务器系统的参数生效。
        ///
        /// </summary>
        private string _is_used_local;
        
        /// <summary>
        /// 主控文件类型
        /// </summary>
        private string _para_master_type;
        
        /// <summary>
        /// 参数类型
        /// </summary>
        public string para_type
        {
            get
            {
                return this._para_type;
            }
            set
            {
                this._para_type = value;
            }
        }
        
        /// <summary>
        /// 参数子类型
        /// </summary>
        public string para_sub_type
        {
            get
            {
                return this._para_sub_type;
            }
            set
            {
                this._para_sub_type = value;
            }
        }
        
        /// <summary>
        /// 全路径名称
        /// </summary>
        public string para_file_name
        {
            get
            {
                return this._para_file_name;
            }
            set
            {
                this._para_file_name = value;
            }
        }
        
        /// <summary>
        /// 使用4个字节（32位）位图描述，每一位表示一种设备类型，置1表示为该类设备使用，置0表示不使用。
        ///bit00：服务器
        ///bit01：工作站
        ///bit02：网络设备
        ///bit03：ups
        ///bit04：e/s
        ///bit05：agm
        ///bit06：bom
        ///bit07：tvm
        ///bit08：avm
        ///bit09：tcm
        ///bit10：pca
        ///bit11~bit31：预留
        ///
        /// </summary>
        public string user_type_bit_map
        {
            get
            {
                return this._user_type_bit_map;
            }
            set
            {
                this._user_type_bit_map = value;
            }
        }
        
        /// <summary>
        /// 1：acc
        ///2:  lcc
        ///
        /// </summary>
        public string para_source
        {
            get
            {
                return this._para_source;
            }
            set
            {
                this._para_source = value;
            }
        }
        
        /// <summary>
        /// 1：即时生效，0：不即时生效
        /// </summary>
        public string is_instant_active
        {
            get
            {
                return this._is_instant_active;
            }
            set
            {
                this._is_instant_active = value;
            }
        }
        
        /// <summary>
        /// 1：即时参数，0：非即时参数
        /// </summary>
        public string is_instant_para
        {
            get
            {
                return this._is_instant_para;
            }
            set
            {
                this._is_instant_para = value;
            }
        }
        
        /// <summary>
        /// 描述参数的作用
        /// </summary>
        public string para_desc
        {
            get
            {
                return this._para_desc;
            }
            set
            {
                this._para_desc = value;
            }
        }
        
        /// <summary>
        /// 1：为本系统使用该参数，0：为本系统不使用该参数。
        ///注：主要用于服务器系统的参数生效。
        ///
        /// </summary>
        public string is_used_local
        {
            get
            {
                return this._is_used_local;
            }
            set
            {
                this._is_used_local = value;
            }
        }
        
        /// <summary>
        /// 主控文件类型
        /// </summary>
        public string para_master_type
        {
            get
            {
                return this._para_master_type;
            }
            set
            {
                this._para_master_type = value;
            }
        }
    }
}
