//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：data_file_up_info_his
    /// </summary>
    public class DataFileUpInfoHis
    {
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        private string _file_type;
        
        /// <summary>
        /// COLUMN: FILE_SUB_TYPE
        /// </summary>
        private string _file_sub_type;
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        private string _file_name;
        
        /// <summary>
        /// COLUMN: FILE_SN
        /// </summary>
        private string _file_sn;
        
        /// <summary>
        /// COLUMN: SET_DATE
        /// </summary>
        private string _set_date;
        
        /// <summary>
        /// COLUMN: SET_TIME
        /// </summary>
        private string _set_time;
        
        /// <summary>
        /// COLUMN: UP_DATE
        /// </summary>
        private string _up_date;
        
        /// <summary>
        /// COLUMN: UP_TIME
        /// </summary>
        private string _up_time;
        
        /// <summary>
        /// COLUMN: UP_NUM
        /// </summary>
        private decimal _up_num;
        
        /// <summary>
        /// COLUMN: UP_RESULT
        /// </summary>
        private string _up_result;
        
        /// <summary>
        /// COLUMN: ERROR_CODE
        /// </summary>
        private string _error_code;
        
        /// <summary>
        /// COLUMN: RECORD_NUM
        /// </summary>
        private decimal _record_num;
        
        /// <summary>
        /// COLUMN: AUDIT_FLAG
        /// </summary>
        private string _audit_flag;
        
        /// <summary>
        /// 运营日
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        public string file_type
        {
            get
            {
                return this._file_type;
            }
            set
            {
                this._file_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_SUB_TYPE
        /// </summary>
        public string file_sub_type
        {
            get
            {
                return this._file_sub_type;
            }
            set
            {
                this._file_sub_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        public string file_name
        {
            get
            {
                return this._file_name;
            }
            set
            {
                this._file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_SN
        /// </summary>
        public string file_sn
        {
            get
            {
                return this._file_sn;
            }
            set
            {
                this._file_sn = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_DATE
        /// </summary>
        public string set_date
        {
            get
            {
                return this._set_date;
            }
            set
            {
                this._set_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_TIME
        /// </summary>
        public string set_time
        {
            get
            {
                return this._set_time;
            }
            set
            {
                this._set_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UP_DATE
        /// </summary>
        public string up_date
        {
            get
            {
                return this._up_date;
            }
            set
            {
                this._up_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UP_TIME
        /// </summary>
        public string up_time
        {
            get
            {
                return this._up_time;
            }
            set
            {
                this._up_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UP_NUM
        /// </summary>
        public decimal up_num
        {
            get
            {
                return this._up_num;
            }
            set
            {
                this._up_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UP_RESULT
        /// </summary>
        public string up_result
        {
            get
            {
                return this._up_result;
            }
            set
            {
                this._up_result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ERROR_CODE
        /// </summary>
        public string error_code
        {
            get
            {
                return this._error_code;
            }
            set
            {
                this._error_code = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RECORD_NUM
        /// </summary>
        public decimal record_num
        {
            get
            {
                return this._record_num;
            }
            set
            {
                this._record_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AUDIT_FLAG
        /// </summary>
        public string audit_flag
        {
            get
            {
                return this._audit_flag;
            }
            set
            {
                this._audit_flag = value;
            }
        }
        
        /// <summary>
        /// 运营日
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
    }
}
