//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：data_oper_settlement_info
    /// </summary>
    public class DataOperSettlementInfo
    {
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// 车站id
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// 操作员id
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// 运营日
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// 营收金额:(单位：分)
        /// </summary>
        private decimal _sys_rece_money;
        
        /// <summary>
        /// 备用金:(单位：分)
        /// </summary>
        private decimal _in_oper_money;
        
        /// <summary>
        /// 实际还款:(单位：分)
        /// </summary>
        private decimal _real_rece_money;
        
        /// <summary>
        /// 更新日期
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// 更新时间
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// 见《01系统编码》
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// 车站id
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// 操作员id
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// 运营日
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// 营收金额:(单位：分)
        /// </summary>
        public decimal sys_rece_money
        {
            get
            {
                return this._sys_rece_money;
            }
            set
            {
                this._sys_rece_money = value;
            }
        }
        
        /// <summary>
        /// 备用金:(单位：分)
        /// </summary>
        public decimal in_oper_money
        {
            get
            {
                return this._in_oper_money;
            }
            set
            {
                this._in_oper_money = value;
            }
        }
        
        /// <summary>
        /// 实际还款:(单位：分)
        /// </summary>
        public decimal real_rece_money
        {
            get
            {
                return this._real_rece_money;
            }
            set
            {
                this._real_rece_money = value;
            }
        }
        
        /// <summary>
        /// 更新日期
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
