//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9145
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFC.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_dev_version_info
    /// </summary>
    public class ParaDevVersionInfo
    {
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: PARA_TYPE
        /// </summary>
        private string _para_type;
        
        /// <summary>
        /// COLUMN: PARA_VERSION_TYPE
        /// </summary>
        private string _para_version_type;
        
        /// <summary>
        /// COLUMN: PARA_VERSION
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: PARA_FILE_NAME
        /// </summary>
        private string _para_file_name;
        
        /// <summary>
        /// COLUMN: ACTIVE_DATE_TIME
        /// </summary>
        private string _active_date_time;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_TYPE
        /// </summary>
        public string para_type
        {
            get
            {
                return this._para_type;
            }
            set
            {
                this._para_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_VERSION_TYPE
        /// </summary>
        public string para_version_type
        {
            get
            {
                return this._para_version_type;
            }
            set
            {
                this._para_version_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_VERSION
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_FILE_NAME
        /// </summary>
        public string para_file_name
        {
            get
            {
                return this._para_file_name;
            }
            set
            {
                this._para_file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACTIVE_DATE_TIME
        /// </summary>
        public string active_date_time
        {
            get
            {
                return this._active_date_time;
            }
            set
            {
                this._active_date_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
