//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：bank_cash_operate_log
    /// </summary>
    public class BankCashOperateLog
    {
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: DISPATCH_NO
        /// </summary>
        private string _dispatch_no;
        
        /// <summary>
        /// COLUMN: BANK_ID
        /// </summary>
        private string _bank_id;
        
        /// <summary>
        /// COLUMN: BANK_CASH_NO
        /// </summary>
        private string _bank_cash_no;
        
        /// <summary>
        /// COLUMN: CASH_TYPE
        /// </summary>
        private string _cash_type;
        
        /// <summary>
        /// COLUMN: DISPATCH_TICK_MONEY
        /// </summary>
        private string _dispatch_tick_money;
        
        /// <summary>
        /// COLUMN: MONEY
        /// </summary>
        private string _money;
        
        /// <summary>
        /// COLUMN: DISPATCH_NO_STATUS
        /// </summary>
        private string _dispatch_no_status;
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        private string _remark;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DISPATCH_NO
        /// </summary>
        public string dispatch_no
        {
            get
            {
                return this._dispatch_no;
            }
            set
            {
                this._dispatch_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BANK_ID
        /// </summary>
        public string bank_id
        {
            get
            {
                return this._bank_id;
            }
            set
            {
                this._bank_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BANK_CASH_NO
        /// </summary>
        public string bank_cash_no
        {
            get
            {
                return this._bank_cash_no;
            }
            set
            {
                this._bank_cash_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CASH_TYPE
        /// </summary>
        public string cash_type
        {
            get
            {
                return this._cash_type;
            }
            set
            {
                this._cash_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DISPATCH_TICK_MONEY
        /// </summary>
        public string dispatch_tick_money
        {
            get
            {
                return this._dispatch_tick_money;
            }
            set
            {
                this._dispatch_tick_money = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MONEY
        /// </summary>
        public string money
        {
            get
            {
                return this._money;
            }
            set
            {
                this._money = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DISPATCH_NO_STATUS
        /// </summary>
        public string dispatch_no_status
        {
            get
            {
                return this._dispatch_no_status;
            }
            set
            {
                this._dispatch_no_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this._remark = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
    }
}
