//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_status_id_info
    /// </summary>
    public class BasiStatusIdInfo
    {
        
        /// <summary>
        /// COLUMN: CSS_STATUS_ID
        /// </summary>
        private string _css_status_id;
        
        /// <summary>
        /// COLUMN: CSS_STATUS_ID_NAME
        /// </summary>
        private string _css_status_id_name;
        
        /// <summary>
        /// COLUMN: CSS_STATUS_VALUE
        /// </summary>
        private string _css_status_value;
        
        /// <summary>
        /// COLUMN: CSS_STATUS_VALUE_NAME
        /// </summary>
        private string _css_status_value_name;
        
        /// <summary>
        /// COLUMN: STATUS_ID
        /// </summary>
        private string _status_id;
        
        /// <summary>
        /// COLUMN: STATUS_ID_NAME
        /// </summary>
        private string _status_id_name;
        
        /// <summary>
        /// COLUMN: STATUS_VALUE
        /// </summary>
        private string _status_value;
        
        /// <summary>
        /// COLUMN: STATUS_VALUE_NAME
        /// </summary>
        private string _status_value_name;
        
        /// <summary>
        /// COLUMN: STATUS_LEVEL
        /// </summary>
        private string _status_level;
        
        /// <summary>
        /// COLUMN: STATUS_VISIABLE
        /// </summary>
        private string _status_visiable;
        
        /// <summary>
        /// COLUMN: ALARM_STYLE
        /// </summary>
        private string _alarm_style;
        
        /// <summary>
        /// COLUMN: LOG_FLAG
        /// </summary>
        private string _log_flag;
        
        /// <summary>
        /// COLUMN: CSS_STATUS_ID
        /// </summary>
        public string css_status_id
        {
            get
            {
                return this._css_status_id;
            }
            set
            {
                this._css_status_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CSS_STATUS_ID_NAME
        /// </summary>
        public string css_status_id_name
        {
            get
            {
                return this._css_status_id_name;
            }
            set
            {
                this._css_status_id_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CSS_STATUS_VALUE
        /// </summary>
        public string css_status_value
        {
            get
            {
                return this._css_status_value;
            }
            set
            {
                this._css_status_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CSS_STATUS_VALUE_NAME
        /// </summary>
        public string css_status_value_name
        {
            get
            {
                return this._css_status_value_name;
            }
            set
            {
                this._css_status_value_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_ID
        /// </summary>
        public string status_id
        {
            get
            {
                return this._status_id;
            }
            set
            {
                this._status_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_ID_NAME
        /// </summary>
        public string status_id_name
        {
            get
            {
                return this._status_id_name;
            }
            set
            {
                this._status_id_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_VALUE
        /// </summary>
        public string status_value
        {
            get
            {
                return this._status_value;
            }
            set
            {
                this._status_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_VALUE_NAME
        /// </summary>
        public string status_value_name
        {
            get
            {
                return this._status_value_name;
            }
            set
            {
                this._status_value_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_LEVEL
        /// </summary>
        public string status_level
        {
            get
            {
                return this._status_level;
            }
            set
            {
                this._status_level = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS_VISIABLE
        /// </summary>
        public string status_visiable
        {
            get
            {
                return this._status_visiable;
            }
            set
            {
                this._status_visiable = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ALARM_STYLE
        /// </summary>
        public string alarm_style
        {
            get
            {
                return this._alarm_style;
            }
            set
            {
                this._alarm_style = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LOG_FLAG
        /// </summary>
        public string log_flag
        {
            get
            {
                return this._log_flag;
            }
            set
            {
                this._log_flag = value;
            }
        }
    }
}
