//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_provider_info
    /// </summary>
    public class BasiProviderInfo
    {
        
        /// <summary>
        /// COLUMN: PROVIDER_ID
        /// </summary>
        private string _provider_id;
        
        /// <summary>
        /// COLUMN: MC_DEP_NAME
        /// </summary>
        private string _mc_dep_name;
        
        /// <summary>
        /// COLUMN: PROVIDER_ADDRESS
        /// </summary>
        private string _provider_address;
        
        /// <summary>
        /// COLUMN: PHONE
        /// </summary>
        private string _phone;
        
        /// <summary>
        /// COLUMN: CONTRACT_PERSON
        /// </summary>
        private string _contract_person;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: PROVIDER_ID
        /// </summary>
        public string provider_id
        {
            get
            {
                return this._provider_id;
            }
            set
            {
                this._provider_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MC_DEP_NAME
        /// </summary>
        public string mc_dep_name
        {
            get
            {
                return this._mc_dep_name;
            }
            set
            {
                this._mc_dep_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PROVIDER_ADDRESS
        /// </summary>
        public string provider_address
        {
            get
            {
                return this._provider_address;
            }
            set
            {
                this._provider_address = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PHONE
        /// </summary>
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this._phone = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CONTRACT_PERSON
        /// </summary>
        public string contract_person
        {
            get
            {
                return this._contract_person;
            }
            set
            {
                this._contract_person = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
