//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_off_peak_hours_table
    /// </summary>
    public class BasiOffPeakHoursTable
    {
        
        /// <summary>
        /// COLUMN: DAY_OF_WEEK
        /// </summary>
        private string _day_of_week;
        
        /// <summary>
        /// COLUMN: OFF_PEAK_START_TIME
        /// </summary>
        private string _off_peak_start_time;
        
        /// <summary>
        /// COLUMN: OFF_PEAK_END_TIME
        /// </summary>
        private string _off_peak_end_time;
        
        /// <summary>
        /// COLUMN: DAY_OF_WEEK
        /// </summary>
        public string day_of_week
        {
            get
            {
                return this._day_of_week;
            }
            set
            {
                this._day_of_week = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OFF_PEAK_START_TIME
        /// </summary>
        public string off_peak_start_time
        {
            get
            {
                return this._off_peak_start_time;
            }
            set
            {
                this._off_peak_start_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OFF_PEAK_END_TIME
        /// </summary>
        public string off_peak_end_time
        {
            get
            {
                return this._off_peak_end_time;
            }
            set
            {
                this._off_peak_end_time = value;
            }
        }
    }
}
