//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_mode_code_info
    /// </summary>
    public class BasiModeCodeInfo
    {
        
        /// <summary>
        /// COLUMN: MODE_TYPE
        /// </summary>
        private string _mode_type;
        
        /// <summary>
        /// COLUMN: MODE_TYPE_NAME
        /// </summary>
        private string _mode_type_name;
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        private string _mode_code;
        
        /// <summary>
        /// COLUMN: MODE_NAME
        /// </summary>
        private string _mode_name;
        
        /// <summary>
        /// COLUMN: MODE_TYPE
        /// </summary>
        public string mode_type
        {
            get
            {
                return this._mode_type;
            }
            set
            {
                this._mode_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MODE_TYPE_NAME
        /// </summary>
        public string mode_type_name
        {
            get
            {
                return this._mode_type_name;
            }
            set
            {
                this._mode_type_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        public string mode_code
        {
            get
            {
                return this._mode_code;
            }
            set
            {
                this._mode_code = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MODE_NAME
        /// </summary>
        public string mode_name
        {
            get
            {
                return this._mode_name;
            }
            set
            {
                this._mode_name = value;
            }
        }
    }
}
