//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_dev_part_type_info
    /// </summary>
    public class BasiDevPartTypeInfo
    {
        
        /// <summary>
        /// COLUMN: DEV_PART_ID
        /// </summary>
        private string _dev_part_id;
        
        /// <summary>
        /// COLUMN: DEV_PART_ID_NAME
        /// </summary>
        private string _dev_part_id_name;
        
        /// <summary>
        /// COLUMN: DEV_PART_CHILD_ID
        /// </summary>
        private string _dev_part_child_id;
        
        /// <summary>
        /// COLUMN: DEV_PART_CHILD_ID_NAME
        /// </summary>
        private string _dev_part_child_id_name;
        
        /// <summary>
        /// COLUMN: DEV_PART_ID
        /// </summary>
        public string dev_part_id
        {
            get
            {
                return this._dev_part_id;
            }
            set
            {
                this._dev_part_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEV_PART_ID_NAME
        /// </summary>
        public string dev_part_id_name
        {
            get
            {
                return this._dev_part_id_name;
            }
            set
            {
                this._dev_part_id_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEV_PART_CHILD_ID
        /// </summary>
        public string dev_part_child_id
        {
            get
            {
                return this._dev_part_child_id;
            }
            set
            {
                this._dev_part_child_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEV_PART_CHILD_ID_NAME
        /// </summary>
        public string dev_part_child_id_name
        {
            get
            {
                return this._dev_part_child_id_name;
            }
            set
            {
                this._dev_part_child_id_name = value;
            }
        }
    }
}
