//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：basi_event_id_info
    /// </summary>
    public class BasiEventIdInfo
    {
        
        /// <summary>
        /// COLUMN: EVENT_ID
        /// </summary>
        private string _event_id;
        
        /// <summary>
        /// COLUMN: EVENT_ID_NAME
        /// </summary>
        private string _event_id_name;
        
        /// <summary>
        /// COLUMN: EVENT_LEVEL
        /// </summary>
        private string _event_level;
        
        /// <summary>
        /// COLUMN: EVENT_ID
        /// </summary>
        public string event_id
        {
            get
            {
                return this._event_id;
            }
            set
            {
                this._event_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: EVENT_ID_NAME
        /// </summary>
        public string event_id_name
        {
            get
            {
                return this._event_id_name;
            }
            set
            {
                this._event_id_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: EVENT_LEVEL
        /// </summary>
        public string event_level
        {
            get
            {
                return this._event_level;
            }
            set
            {
                this._event_level = value;
            }
        }
    }
}
