//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：bom_operate_log
    /// </summary>
    public class BomOperateLog
    {
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: DISPATCH_NO
        /// </summary>
        private string _dispatch_no;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: BOM_OPERATOR_ID
        /// </summary>
        private string _bom_operator_id;
        
        /// <summary>
        /// COLUMN: DISPATCH_DIRECTION
        /// </summary>
        private string _dispatch_direction;
        
        /// <summary>
        /// COLUMN: NO_STATUS
        /// </summary>
        private string _no_status;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        private string _remark;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DISPATCH_NO
        /// </summary>
        public string dispatch_no
        {
            get
            {
                return this._dispatch_no;
            }
            set
            {
                this._dispatch_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BOM_OPERATOR_ID
        /// </summary>
        public string bom_operator_id
        {
            get
            {
                return this._bom_operator_id;
            }
            set
            {
                this._bom_operator_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DISPATCH_DIRECTION
        /// </summary>
        public string dispatch_direction
        {
            get
            {
                return this._dispatch_direction;
            }
            set
            {
                this._dispatch_direction = value;
            }
        }
        
        /// <summary>
        /// COLUMN: NO_STATUS
        /// </summary>
        public string no_status
        {
            get
            {
                return this._no_status;
            }
            set
            {
                this._no_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this._remark = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
