//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：data_file_deal_abnormal_info
    /// </summary>
    public class DataFileDealAbnormalInfo
    {
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: UDSN
        /// </summary>
        private string _udsn;
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        private string _file_type;
        
        /// <summary>
        /// COLUMN: FILE_SUB_TYPE
        /// </summary>
        private string _file_sub_type;
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        private string _file_name;
        
        /// <summary>
        /// COLUMN: FILE_SN
        /// </summary>
        private string _file_sn;
        
        /// <summary>
        /// COLUMN: DEAL_DATE
        /// </summary>
        private string _deal_date;
        
        /// <summary>
        /// COLUMN: DEAL_TIME
        /// </summary>
        private string _deal_time;
        
        /// <summary>
        /// COLUMN: DEAL_RESULT
        /// </summary>
        private string _deal_result;
        
        /// <summary>
        /// COLUMN: RECORD_NO
        /// </summary>
        private string _record_no;
        
        /// <summary>
        /// COLUMN: RETRY_TIMES
        /// </summary>
        private string _retry_times;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UDSN
        /// </summary>
        public string udsn
        {
            get
            {
                return this._udsn;
            }
            set
            {
                this._udsn = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        public string file_type
        {
            get
            {
                return this._file_type;
            }
            set
            {
                this._file_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_SUB_TYPE
        /// </summary>
        public string file_sub_type
        {
            get
            {
                return this._file_sub_type;
            }
            set
            {
                this._file_sub_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        public string file_name
        {
            get
            {
                return this._file_name;
            }
            set
            {
                this._file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_SN
        /// </summary>
        public string file_sn
        {
            get
            {
                return this._file_sn;
            }
            set
            {
                this._file_sn = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEAL_DATE
        /// </summary>
        public string deal_date
        {
            get
            {
                return this._deal_date;
            }
            set
            {
                this._deal_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEAL_TIME
        /// </summary>
        public string deal_time
        {
            get
            {
                return this._deal_time;
            }
            set
            {
                this._deal_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEAL_RESULT
        /// </summary>
        public string deal_result
        {
            get
            {
                return this._deal_result;
            }
            set
            {
                this._deal_result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RECORD_NO
        /// </summary>
        public string record_no
        {
            get
            {
                return this._record_no;
            }
            set
            {
                this._record_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RETRY_TIMES
        /// </summary>
        public string retry_times
        {
            get
            {
                return this._retry_times;
            }
            set
            {
                this._retry_times = value;
            }
        }
    }
}
