//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：data_request_reupload
    /// </summary>
    public class DataRequestReupload
    {
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        private string _file_type;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: START_UDSN
        /// </summary>
        private string _start_udsn;
        
        /// <summary>
        /// COLUMN: END_UDSN
        /// </summary>
        private string _end_udsn;
        
        /// <summary>
        /// COLUMN: GEN_DATE_TIME
        /// </summary>
        private string _gen_date_time;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        public string file_type
        {
            get
            {
                return this._file_type;
            }
            set
            {
                this._file_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: START_UDSN
        /// </summary>
        public string start_udsn
        {
            get
            {
                return this._start_udsn;
            }
            set
            {
                this._start_udsn = value;
            }
        }
        
        /// <summary>
        /// COLUMN: END_UDSN
        /// </summary>
        public string end_udsn
        {
            get
            {
                return this._end_udsn;
            }
            set
            {
                this._end_udsn = value;
            }
        }
        
        /// <summary>
        /// COLUMN: GEN_DATE_TIME
        /// </summary>
        public string gen_date_time
        {
            get
            {
                return this._gen_date_time;
            }
            set
            {
                this._gen_date_time = value;
            }
        }
    }
}
