//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：data_deferred_refund_apply
    /// </summary>
    public class DataDeferredRefundApply
    {
        
        /// <summary>
        /// COLUMN: TRAN_TYPE
        /// </summary>
        private string _tran_type;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: DEVICE_TYPE
        /// </summary>
        private string _device_type;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        private string _tick_type;
        
        /// <summary>
        /// COLUMN: TICKET_LOGICAL_ID
        /// </summary>
        private string _ticket_logical_id;
        
        /// <summary>
        /// COLUMN: TICKET_PHY_ID
        /// </summary>
        private string _ticket_phy_id;
        
        /// <summary>
        /// COLUMN: SURFACE_NO
        /// </summary>
        private string _surface_no;
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        private string _occur_date;
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        private string _occur_time;
        
        /// <summary>
        /// COLUMN: RECEIPT_ID
        /// </summary>
        private string _receipt_id;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: PASSENGER_NAME
        /// </summary>
        private string _passenger_name;
        
        /// <summary>
        /// COLUMN: PASSENGER_TEL
        /// </summary>
        private string _passenger_tel;
        
        /// <summary>
        /// COLUMN: PAPERS_TYPE
        /// </summary>
        private string _papers_type;
        
        /// <summary>
        /// COLUMN: PERSONAL_ID
        /// </summary>
        private string _personal_id;
        
        /// <summary>
        /// COLUMN: IS_BROKEN
        /// </summary>
        private string _is_broken;
        
        /// <summary>
        /// COLUMN: SHIFT_ID
        /// </summary>
        private string _shift_id;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: APP_FLAG
        /// </summary>
        private string _app_flag;
        
        /// <summary>
        /// COLUMN: TRAN_TYPE
        /// </summary>
        public string tran_type
        {
            get
            {
                return this._tran_type;
            }
            set
            {
                this._tran_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_TYPE
        /// </summary>
        public string device_type
        {
            get
            {
                return this._device_type;
            }
            set
            {
                this._device_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        public string tick_type
        {
            get
            {
                return this._tick_type;
            }
            set
            {
                this._tick_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICKET_LOGICAL_ID
        /// </summary>
        public string ticket_logical_id
        {
            get
            {
                return this._ticket_logical_id;
            }
            set
            {
                this._ticket_logical_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICKET_PHY_ID
        /// </summary>
        public string ticket_phy_id
        {
            get
            {
                return this._ticket_phy_id;
            }
            set
            {
                this._ticket_phy_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SURFACE_NO
        /// </summary>
        public string surface_no
        {
            get
            {
                return this._surface_no;
            }
            set
            {
                this._surface_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        public string occur_date
        {
            get
            {
                return this._occur_date;
            }
            set
            {
                this._occur_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        public string occur_time
        {
            get
            {
                return this._occur_time;
            }
            set
            {
                this._occur_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RECEIPT_ID
        /// </summary>
        public string receipt_id
        {
            get
            {
                return this._receipt_id;
            }
            set
            {
                this._receipt_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PASSENGER_NAME
        /// </summary>
        public string passenger_name
        {
            get
            {
                return this._passenger_name;
            }
            set
            {
                this._passenger_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PASSENGER_TEL
        /// </summary>
        public string passenger_tel
        {
            get
            {
                return this._passenger_tel;
            }
            set
            {
                this._passenger_tel = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PAPERS_TYPE
        /// </summary>
        public string papers_type
        {
            get
            {
                return this._papers_type;
            }
            set
            {
                this._papers_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PERSONAL_ID
        /// </summary>
        public string personal_id
        {
            get
            {
                return this._personal_id;
            }
            set
            {
                this._personal_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IS_BROKEN
        /// </summary>
        public string is_broken
        {
            get
            {
                return this._is_broken;
            }
            set
            {
                this._is_broken = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SHIFT_ID
        /// </summary>
        public string shift_id
        {
            get
            {
                return this._shift_id;
            }
            set
            {
                this._shift_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: APP_FLAG
        /// </summary>
        public string app_flag
        {
            get
            {
                return this._app_flag;
            }
            set
            {
                this._app_flag = value;
            }
        }
    }
}
