//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：dev_auto_cmd_group
    /// </summary>
    public class DevAutoCmdGroup
    {
        
        /// <summary>
        /// COLUMN: CMD_ID
        /// </summary>
        private string _cmd_id;
        
        /// <summary>
        /// COLUMN: CMD_NAME
        /// </summary>
        private string _cmd_name;
        
        /// <summary>
        /// COLUMN: CMD_ID
        /// </summary>
        public string cmd_id
        {
            get
            {
                return this._cmd_id;
            }
            set
            {
                this._cmd_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CMD_NAME
        /// </summary>
        public string cmd_name
        {
            get
            {
                return this._cmd_name;
            }
            set
            {
                this._cmd_name = value;
            }
        }
    }
}
