//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：dev_sam_id_info
    /// </summary>
    public class DevSamIdInfo
    {
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: SAM_TYPE
        /// </summary>
        private string _sam_type;
        
        /// <summary>
        /// COLUMN: SVT_VALUE
        /// </summary>
        private string _svt_value;
        
        /// <summary>
        /// COLUMN: SJT_VALUE
        /// </summary>
        private string _sjt_value;
        
        /// <summary>
        /// COLUMN: TCT_VALUE
        /// </summary>
        private string _tct_value;
        
        /// <summary>
        /// COLUMN: CUR_SAM_ID
        /// </summary>
        private string _cur_sam_id;
        
        /// <summary>
        /// COLUMN: REG_SAM_ID
        /// </summary>
        private string _reg_sam_id;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SAM_TYPE
        /// </summary>
        public string sam_type
        {
            get
            {
                return this._sam_type;
            }
            set
            {
                this._sam_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SVT_VALUE
        /// </summary>
        public string svt_value
        {
            get
            {
                return this._svt_value;
            }
            set
            {
                this._svt_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SJT_VALUE
        /// </summary>
        public string sjt_value
        {
            get
            {
                return this._sjt_value;
            }
            set
            {
                this._sjt_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TCT_VALUE
        /// </summary>
        public string tct_value
        {
            get
            {
                return this._tct_value;
            }
            set
            {
                this._tct_value = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CUR_SAM_ID
        /// </summary>
        public string cur_sam_id
        {
            get
            {
                return this._cur_sam_id;
            }
            set
            {
                this._cur_sam_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REG_SAM_ID
        /// </summary>
        public string reg_sam_id
        {
            get
            {
                return this._reg_sam_id;
            }
            set
            {
                this._reg_sam_id = value;
            }
        }
    }
}
