//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：maintain_area_info
    /// </summary>
    public class MaintainAreaInfo
    {
        
        /// <summary>
        /// COLUMN: MAINTAIN_AREA_ID
        /// </summary>
        private string _maintain_area_id;
        
        /// <summary>
        /// COLUMN: MAINTAIN_AREA_NAME
        /// </summary>
        private string _maintain_area_name;
        
        /// <summary>
        /// COLUMN: AREA_CONTRACTOR
        /// </summary>
        private string _area_contractor;
        
        /// <summary>
        /// COLUMN: AREA_PHONE_NO
        /// </summary>
        private string _area_phone_no;
        
        /// <summary>
        /// COLUMN: AREA_ADDRESS
        /// </summary>
        private string _area_address;
        
        /// <summary>
        /// COLUMN: UPDATE_OPERATOR
        /// </summary>
        private string _update_operator;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: MAINTAIN_AREA_ID
        /// </summary>
        public string maintain_area_id
        {
            get
            {
                return this._maintain_area_id;
            }
            set
            {
                this._maintain_area_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MAINTAIN_AREA_NAME
        /// </summary>
        public string maintain_area_name
        {
            get
            {
                return this._maintain_area_name;
            }
            set
            {
                this._maintain_area_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AREA_CONTRACTOR
        /// </summary>
        public string area_contractor
        {
            get
            {
                return this._area_contractor;
            }
            set
            {
                this._area_contractor = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AREA_PHONE_NO
        /// </summary>
        public string area_phone_no
        {
            get
            {
                return this._area_phone_no;
            }
            set
            {
                this._area_phone_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: AREA_ADDRESS
        /// </summary>
        public string area_address
        {
            get
            {
                return this._area_address;
            }
            set
            {
                this._area_address = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_OPERATOR
        /// </summary>
        public string update_operator
        {
            get
            {
                return this._update_operator;
            }
            set
            {
                this._update_operator = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
