//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：maintain_rpt_track_info
    /// </summary>
    public class MaintainRptTrackInfo
    {
        
        /// <summary>
        /// COLUMN: FAULT_TRACK_ID
        /// </summary>
        private string _fault_track_id;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: FAULT_DOC_ID
        /// </summary>
        private string _fault_doc_id;
        
        /// <summary>
        /// COLUMN: FAULT_INDOOR_DOC_ID
        /// </summary>
        private string _fault_indoor_doc_id;
        
        /// <summary>
        /// COLUMN: STATUS
        /// </summary>
        private string _status;
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        private string _remark;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: FAULT_TRACK_ID
        /// </summary>
        public string fault_track_id
        {
            get
            {
                return this._fault_track_id;
            }
            set
            {
                this._fault_track_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FAULT_DOC_ID
        /// </summary>
        public string fault_doc_id
        {
            get
            {
                return this._fault_doc_id;
            }
            set
            {
                this._fault_doc_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FAULT_INDOOR_DOC_ID
        /// </summary>
        public string fault_indoor_doc_id
        {
            get
            {
                return this._fault_indoor_doc_id;
            }
            set
            {
                this._fault_indoor_doc_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATUS
        /// </summary>
        public string status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this._remark = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
