//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：mode_log_info
    /// </summary>
    public class ModeLogInfo
    {
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        private string _mode_code;
        
        /// <summary>
        /// COLUMN: SET_ORIGIN
        /// </summary>
        private string _set_origin;
        
        /// <summary>
        /// COLUMN: SET_DATE
        /// </summary>
        private string _set_date;
        
        /// <summary>
        /// COLUMN: SET_TIME
        /// </summary>
        private string _set_time;
        
        /// <summary>
        /// COLUMN: SET_OPER_ID
        /// </summary>
        private string _set_oper_id;
        
        /// <summary>
        /// COLUMN: RELEASE_DATE
        /// </summary>
        private string _release_date;
        
        /// <summary>
        /// COLUMN: RELEASE_TIME
        /// </summary>
        private string _release_time;
        
        /// <summary>
        /// COLUMN: RELEASE_OPER_ID
        /// </summary>
        private string _release_oper_id;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MODE_CODE
        /// </summary>
        public string mode_code
        {
            get
            {
                return this._mode_code;
            }
            set
            {
                this._mode_code = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_ORIGIN
        /// </summary>
        public string set_origin
        {
            get
            {
                return this._set_origin;
            }
            set
            {
                this._set_origin = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_DATE
        /// </summary>
        public string set_date
        {
            get
            {
                return this._set_date;
            }
            set
            {
                this._set_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_TIME
        /// </summary>
        public string set_time
        {
            get
            {
                return this._set_time;
            }
            set
            {
                this._set_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SET_OPER_ID
        /// </summary>
        public string set_oper_id
        {
            get
            {
                return this._set_oper_id;
            }
            set
            {
                this._set_oper_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RELEASE_DATE
        /// </summary>
        public string release_date
        {
            get
            {
                return this._release_date;
            }
            set
            {
                this._release_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RELEASE_TIME
        /// </summary>
        public string release_time
        {
            get
            {
                return this._release_time;
            }
            set
            {
                this._release_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RELEASE_OPER_ID
        /// </summary>
        public string release_oper_id
        {
            get
            {
                return this._release_oper_id;
            }
            set
            {
                this._release_oper_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
