//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：para_version_info
    /// </summary>
    public class ParaVersionInfo
    {
        
        /// <summary>
        /// COLUMN: PARA_TYPE
        /// </summary>
        private string _para_type;
        
        /// <summary>
        /// COLUMN: PARA_VERSION
        /// </summary>
        private string _para_version;
        
        /// <summary>
        /// COLUMN: MASTER_PARA_TYPE
        /// </summary>
        private string _master_para_type;
        
        /// <summary>
        /// COLUMN: MASTER_PARA_VERSION
        /// </summary>
        private string _master_para_version;
        
        /// <summary>
        /// COLUMN: PARA_OR_SOFT_FLAG
        /// </summary>
        private string _para_or_soft_flag;
        
        /// <summary>
        /// COLUMN: PARA_VERSION_TYPE
        /// </summary>
        private string _para_version_type;
        
        /// <summary>
        /// COLUMN: PARA_MODE
        /// </summary>
        private string _para_mode;
        
        /// <summary>
        /// COLUMN: PARA_FILE_NAME
        /// </summary>
        private string _para_file_name;
        
        /// <summary>
        /// COLUMN: PARA_FILE_MD5
        /// </summary>
        private string _para_file_md5;
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        private string _occur_date;
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        private string _occur_time;
        
        /// <summary>
        /// COLUMN: ACTIVE_DATE
        /// </summary>
        private string _active_date;
        
        /// <summary>
        /// COLUMN: ACTIVE_TIME
        /// </summary>
        private string _active_time;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: PARA_TYPE
        /// </summary>
        public string para_type
        {
            get
            {
                return this._para_type;
            }
            set
            {
                this._para_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_VERSION
        /// </summary>
        public string para_version
        {
            get
            {
                return this._para_version;
            }
            set
            {
                this._para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MASTER_PARA_TYPE
        /// </summary>
        public string master_para_type
        {
            get
            {
                return this._master_para_type;
            }
            set
            {
                this._master_para_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MASTER_PARA_VERSION
        /// </summary>
        public string master_para_version
        {
            get
            {
                return this._master_para_version;
            }
            set
            {
                this._master_para_version = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_OR_SOFT_FLAG
        /// </summary>
        public string para_or_soft_flag
        {
            get
            {
                return this._para_or_soft_flag;
            }
            set
            {
                this._para_or_soft_flag = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_VERSION_TYPE
        /// </summary>
        public string para_version_type
        {
            get
            {
                return this._para_version_type;
            }
            set
            {
                this._para_version_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_MODE
        /// </summary>
        public string para_mode
        {
            get
            {
                return this._para_mode;
            }
            set
            {
                this._para_mode = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_FILE_NAME
        /// </summary>
        public string para_file_name
        {
            get
            {
                return this._para_file_name;
            }
            set
            {
                this._para_file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: PARA_FILE_MD5
        /// </summary>
        public string para_file_md5
        {
            get
            {
                return this._para_file_md5;
            }
            set
            {
                this._para_file_md5 = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        public string occur_date
        {
            get
            {
                return this._occur_date;
            }
            set
            {
                this._occur_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        public string occur_time
        {
            get
            {
                return this._occur_time;
            }
            set
            {
                this._occur_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACTIVE_DATE
        /// </summary>
        public string active_date
        {
            get
            {
                return this._active_date;
            }
            set
            {
                this._active_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACTIVE_TIME
        /// </summary>
        public string active_time
        {
            get
            {
                return this._active_time;
            }
            set
            {
                this._active_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
