//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：pca_oper_detail
    /// </summary>
    public class PcaOperDetail
    {
        
        /// <summary>
        /// COLUMN: OPER_SEQ
        /// </summary>
        private string _oper_seq;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: OPER_TYPE
        /// </summary>
        private string _oper_type;
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        private string _tick_type;
        
        /// <summary>
        /// COLUMN: TICK_NUM
        /// </summary>
        private string _tick_num;
        
        /// <summary>
        /// COLUMN: OPER_SEQ
        /// </summary>
        public string oper_seq
        {
            get
            {
                return this._oper_seq;
            }
            set
            {
                this._oper_seq = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPER_TYPE
        /// </summary>
        public string oper_type
        {
            get
            {
                return this._oper_type;
            }
            set
            {
                this._oper_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        public string tick_type
        {
            get
            {
                return this._tick_type;
            }
            set
            {
                this._tick_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_NUM
        /// </summary>
        public string tick_num
        {
            get
            {
                return this._tick_num;
            }
            set
            {
                this._tick_num = value;
            }
        }
    }
}
