//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：priv_role_info
    /// </summary>
    public class PrivRoleInfo
    {
        
        /// <summary>
        /// COLUMN: ROLE_ID
        /// </summary>
        private string _role_id;
        
        /// <summary>
        /// COLUMN: ROLE_STATUS
        /// </summary>
        private string _role_status;
        
        /// <summary>
        /// COLUMN: ROLE_NAME
        /// </summary>
        private string _role_name;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: ROLE_ID
        /// </summary>
        public string role_id
        {
            get
            {
                return this._role_id;
            }
            set
            {
                this._role_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ROLE_STATUS
        /// </summary>
        public string role_status
        {
            get
            {
                return this._role_status;
            }
            set
            {
                this._role_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ROLE_NAME
        /// </summary>
        public string role_name
        {
            get
            {
                return this._role_name;
            }
            set
            {
                this._role_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
    }
}
