//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：priv_function_info
    /// </summary>
    public class PrivFunctionInfo
    {
        
        /// <summary>
        /// COLUMN: FUNCTION_ID
        /// </summary>
        private string _function_id;
        
        /// <summary>
        /// COLUMN: FUNCTION_STATUS
        /// </summary>
        private string _function_status;
        
        /// <summary>
        /// COLUMN: FUNCTION_CATEGORY
        /// </summary>
        private string _function_category;
        
        /// <summary>
        /// COLUMN: FUNCTION_SUB_CATEGORY
        /// </summary>
        private string _function_sub_category;
        
        /// <summary>
        /// COLUMN: DEVICE_TYPE
        /// </summary>
        private string _device_type;
        
        /// <summary>
        /// COLUMN: FUNCTION_NAME
        /// </summary>
        private string _function_name;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: FUNCTION_ID
        /// </summary>
        public string function_id
        {
            get
            {
                return this._function_id;
            }
            set
            {
                this._function_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FUNCTION_STATUS
        /// </summary>
        public string function_status
        {
            get
            {
                return this._function_status;
            }
            set
            {
                this._function_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FUNCTION_CATEGORY
        /// </summary>
        public string function_category
        {
            get
            {
                return this._function_category;
            }
            set
            {
                this._function_category = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FUNCTION_SUB_CATEGORY
        /// </summary>
        public string function_sub_category
        {
            get
            {
                return this._function_sub_category;
            }
            set
            {
                this._function_sub_category = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_TYPE
        /// </summary>
        public string device_type
        {
            get
            {
                return this._device_type;
            }
            set
            {
                this._device_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FUNCTION_NAME
        /// </summary>
        public string function_name
        {
            get
            {
                return this._function_name;
            }
            set
            {
                this._function_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
    }
}
