//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：reco_pkl
    /// </summary>
    public class RecoPkl
    {
        
        /// <summary>
        /// COLUMN: RECO_DATE
        /// </summary>
        private string _reco_date;
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        private string _file_type;
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        private string _file_name;
        
        /// <summary>
        /// COLUMN: LC_FILE_NAME
        /// </summary>
        private string _lc_file_name;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: FILE_STATUS
        /// </summary>
        private string _file_status;
        
        /// <summary>
        /// COLUMN: UP_DATE_TIME
        /// </summary>
        private string _up_date_time;
        
        /// <summary>
        /// COLUMN: TOTAL_QTY
        /// </summary>
        private string _total_qty;
        
        /// <summary>
        /// COLUMN: DEALT_QTY
        /// </summary>
        private string _dealt_qty;
        
        /// <summary>
        /// COLUMN: NORMAL_QTY
        /// </summary>
        private string _normal_qty;
        
        /// <summary>
        /// COLUMN: ABNORMAL_QTY
        /// </summary>
        private string _abnormal_qty;
        
        /// <summary>
        /// COLUMN: TEST_QTY
        /// </summary>
        private string _test_qty;
        
        /// <summary>
        /// COLUMN: CLEAR_ERR_QTY
        /// </summary>
        private string _clear_err_qty;
        
        /// <summary>
        /// COLUMN: LC_QTY
        /// </summary>
        private string _lc_qty;
        
        /// <summary>
        /// COLUMN: LC_UP_RESULT
        /// </summary>
        private string _lc_up_result;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: RECO_DATE
        /// </summary>
        public string reco_date
        {
            get
            {
                return this._reco_date;
            }
            set
            {
                this._reco_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_TYPE
        /// </summary>
        public string file_type
        {
            get
            {
                return this._file_type;
            }
            set
            {
                this._file_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_NAME
        /// </summary>
        public string file_name
        {
            get
            {
                return this._file_name;
            }
            set
            {
                this._file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LC_FILE_NAME
        /// </summary>
        public string lc_file_name
        {
            get
            {
                return this._lc_file_name;
            }
            set
            {
                this._lc_file_name = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: FILE_STATUS
        /// </summary>
        public string file_status
        {
            get
            {
                return this._file_status;
            }
            set
            {
                this._file_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UP_DATE_TIME
        /// </summary>
        public string up_date_time
        {
            get
            {
                return this._up_date_time;
            }
            set
            {
                this._up_date_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TOTAL_QTY
        /// </summary>
        public string total_qty
        {
            get
            {
                return this._total_qty;
            }
            set
            {
                this._total_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEALT_QTY
        /// </summary>
        public string dealt_qty
        {
            get
            {
                return this._dealt_qty;
            }
            set
            {
                this._dealt_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: NORMAL_QTY
        /// </summary>
        public string normal_qty
        {
            get
            {
                return this._normal_qty;
            }
            set
            {
                this._normal_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ABNORMAL_QTY
        /// </summary>
        public string abnormal_qty
        {
            get
            {
                return this._abnormal_qty;
            }
            set
            {
                this._abnormal_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TEST_QTY
        /// </summary>
        public string test_qty
        {
            get
            {
                return this._test_qty;
            }
            set
            {
                this._test_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CLEAR_ERR_QTY
        /// </summary>
        public string clear_err_qty
        {
            get
            {
                return this._clear_err_qty;
            }
            set
            {
                this._clear_err_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LC_QTY
        /// </summary>
        public string lc_qty
        {
            get
            {
                return this._lc_qty;
            }
            set
            {
                this._lc_qty = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LC_UP_RESULT
        /// </summary>
        public string lc_up_result
        {
            get
            {
                return this._lc_up_result;
            }
            set
            {
                this._lc_up_result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
