//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：run_execute_info
    /// </summary>
    public class RunExecuteInfo
    {
        
        /// <summary>
        /// COLUMN: RUN_TASK_ID
        /// </summary>
        private string _run_task_id;
        
        /// <summary>
        /// COLUMN: RUN_TASK_FUN
        /// </summary>
        private string _run_task_fun;
        
        /// <summary>
        /// COLUMN: RUN_EXEC_PHASE
        /// </summary>
        private string _run_exec_phase;
        
        /// <summary>
        /// COLUMN: RUN_TASK_EFFECT_FLAG
        /// </summary>
        private string _run_task_effect_flag;
        
        /// <summary>
        /// COLUMN: RUN_EXEC_STATUS
        /// </summary>
        private string _run_exec_status;
        
        /// <summary>
        /// COLUMN: RUN_START_TIME
        /// </summary>
        private string _run_start_time;
        
        /// <summary>
        /// COLUMN: RUN_END_TIME
        /// </summary>
        private string _run_end_time;
        
        /// <summary>
        /// COLUMN: RUN_NEXT_TASK
        /// </summary>
        private string _run_next_task;
        
        /// <summary>
        /// COLUMN: RUN_SINGLE_FLAG
        /// </summary>
        private string _run_single_flag;
        
        /// <summary>
        /// COLUMN: IF_MUST_RUN
        /// </summary>
        private string _if_must_run;
        
        /// <summary>
        /// COLUMN: REMARK_128
        /// </summary>
        private string _remark_128;
        
        /// <summary>
        /// COLUMN: RUN_TASK_ID
        /// </summary>
        public string run_task_id
        {
            get
            {
                return this._run_task_id;
            }
            set
            {
                this._run_task_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_TASK_FUN
        /// </summary>
        public string run_task_fun
        {
            get
            {
                return this._run_task_fun;
            }
            set
            {
                this._run_task_fun = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_EXEC_PHASE
        /// </summary>
        public string run_exec_phase
        {
            get
            {
                return this._run_exec_phase;
            }
            set
            {
                this._run_exec_phase = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_TASK_EFFECT_FLAG
        /// </summary>
        public string run_task_effect_flag
        {
            get
            {
                return this._run_task_effect_flag;
            }
            set
            {
                this._run_task_effect_flag = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_EXEC_STATUS
        /// </summary>
        public string run_exec_status
        {
            get
            {
                return this._run_exec_status;
            }
            set
            {
                this._run_exec_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_START_TIME
        /// </summary>
        public string run_start_time
        {
            get
            {
                return this._run_start_time;
            }
            set
            {
                this._run_start_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_END_TIME
        /// </summary>
        public string run_end_time
        {
            get
            {
                return this._run_end_time;
            }
            set
            {
                this._run_end_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_NEXT_TASK
        /// </summary>
        public string run_next_task
        {
            get
            {
                return this._run_next_task;
            }
            set
            {
                this._run_next_task = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_SINGLE_FLAG
        /// </summary>
        public string run_single_flag
        {
            get
            {
                return this._run_single_flag;
            }
            set
            {
                this._run_single_flag = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IF_MUST_RUN
        /// </summary>
        public string if_must_run
        {
            get
            {
                return this._if_must_run;
            }
            set
            {
                this._if_must_run = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REMARK_128
        /// </summary>
        public string remark_128
        {
            get
            {
                return this._remark_128;
            }
            set
            {
                this._remark_128 = value;
            }
        }
    }
}
