//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：tick_recycle_info
    /// </summary>
    public class TickRecycleInfo
    {
        
        /// <summary>
        /// COLUMN: ORI_DEV
        /// </summary>
        private string _ori_dev;
        
        /// <summary>
        /// COLUMN: DEST_DEV
        /// </summary>
        private string _dest_dev;
        
        /// <summary>
        /// COLUMN: BATCH_NUM
        /// </summary>
        private string _batch_num;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: ORI_DEV
        /// </summary>
        public string ori_dev
        {
            get
            {
                return this._ori_dev;
            }
            set
            {
                this._ori_dev = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEST_DEV
        /// </summary>
        public string dest_dev
        {
            get
            {
                return this._dest_dev;
            }
            set
            {
                this._dest_dev = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BATCH_NUM
        /// </summary>
        public string batch_num
        {
            get
            {
                return this._batch_num;
            }
            set
            {
                this._batch_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
