//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：tick_deferred_replace_refound
    /// </summary>
    public class TickDeferredReplaceRefound
    {
        
        /// <summary>
        /// COLUMN: ACCEPT_NO
        /// </summary>
        private string _accept_no;
        
        /// <summary>
        /// COLUMN: ACCEPT_TYPE
        /// </summary>
        private string _accept_type;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: ACCEPT_DATE
        /// </summary>
        private string _accept_date;
        
        /// <summary>
        /// COLUMN: OPER_ID
        /// </summary>
        private string _oper_id;
        
        /// <summary>
        /// COLUMN: RESULT
        /// </summary>
        private string _result;
        
        /// <summary>
        /// COLUMN: MEDIA_DAMAGE
        /// </summary>
        private string _media_damage;
        
        /// <summary>
        /// COLUMN: DATA_DAMAGE
        /// </summary>
        private string _data_damage;
        
        /// <summary>
        /// COLUMN: INSTANT_FLAG
        /// </summary>
        private string _instant_flag;
        
        /// <summary>
        /// COLUMN: TICK_PHY_TYPE
        /// </summary>
        private string _tick_phy_type;
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        private string _tick_type;
        
        /// <summary>
        /// COLUMN: ISSUE_DATE
        /// </summary>
        private string _issue_date;
        
        /// <summary>
        /// COLUMN: CARD_NO
        /// </summary>
        private string _card_no;
        
        /// <summary>
        /// COLUMN: CARD_BALANCE
        /// </summary>
        private string _card_balance;
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        private string _remark;
        
        /// <summary>
        /// COLUMN: DEAL_DATE
        /// </summary>
        private string _deal_date;
        
        /// <summary>
        /// COLUMN: BALANCE
        /// </summary>
        private string _balance;
        
        /// <summary>
        /// COLUMN: IDENTIFY_RESULT
        /// </summary>
        private string _identify_result;
        
        /// <summary>
        /// COLUMN: IDENTIFY_BALANCE
        /// </summary>
        private string _identify_balance;
        
        /// <summary>
        /// COLUMN: IDENTIFY_DEPOSIT
        /// </summary>
        private string _identify_deposit;
        
        /// <summary>
        /// COLUMN: SERVICE_FEE
        /// </summary>
        private string _service_fee;
        
        /// <summary>
        /// COLUMN: IDENTIFY_REASON
        /// </summary>
        private string _identify_reason;
        
        /// <summary>
        /// COLUMN: DEAL_RESULT
        /// </summary>
        private string _deal_result;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: ACCEPT_NO
        /// </summary>
        public string accept_no
        {
            get
            {
                return this._accept_no;
            }
            set
            {
                this._accept_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACCEPT_TYPE
        /// </summary>
        public string accept_type
        {
            get
            {
                return this._accept_type;
            }
            set
            {
                this._accept_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ACCEPT_DATE
        /// </summary>
        public string accept_date
        {
            get
            {
                return this._accept_date;
            }
            set
            {
                this._accept_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPER_ID
        /// </summary>
        public string oper_id
        {
            get
            {
                return this._oper_id;
            }
            set
            {
                this._oper_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RESULT
        /// </summary>
        public string result
        {
            get
            {
                return this._result;
            }
            set
            {
                this._result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: MEDIA_DAMAGE
        /// </summary>
        public string media_damage
        {
            get
            {
                return this._media_damage;
            }
            set
            {
                this._media_damage = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DATA_DAMAGE
        /// </summary>
        public string data_damage
        {
            get
            {
                return this._data_damage;
            }
            set
            {
                this._data_damage = value;
            }
        }
        
        /// <summary>
        /// COLUMN: INSTANT_FLAG
        /// </summary>
        public string instant_flag
        {
            get
            {
                return this._instant_flag;
            }
            set
            {
                this._instant_flag = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_PHY_TYPE
        /// </summary>
        public string tick_phy_type
        {
            get
            {
                return this._tick_phy_type;
            }
            set
            {
                this._tick_phy_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_TYPE
        /// </summary>
        public string tick_type
        {
            get
            {
                return this._tick_type;
            }
            set
            {
                this._tick_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ISSUE_DATE
        /// </summary>
        public string issue_date
        {
            get
            {
                return this._issue_date;
            }
            set
            {
                this._issue_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CARD_NO
        /// </summary>
        public string card_no
        {
            get
            {
                return this._card_no;
            }
            set
            {
                this._card_no = value;
            }
        }
        
        /// <summary>
        /// COLUMN: CARD_BALANCE
        /// </summary>
        public string card_balance
        {
            get
            {
                return this._card_balance;
            }
            set
            {
                this._card_balance = value;
            }
        }
        
        /// <summary>
        /// COLUMN: REMARK
        /// </summary>
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this._remark = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEAL_DATE
        /// </summary>
        public string deal_date
        {
            get
            {
                return this._deal_date;
            }
            set
            {
                this._deal_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BALANCE
        /// </summary>
        public string balance
        {
            get
            {
                return this._balance;
            }
            set
            {
                this._balance = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IDENTIFY_RESULT
        /// </summary>
        public string identify_result
        {
            get
            {
                return this._identify_result;
            }
            set
            {
                this._identify_result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IDENTIFY_BALANCE
        /// </summary>
        public string identify_balance
        {
            get
            {
                return this._identify_balance;
            }
            set
            {
                this._identify_balance = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IDENTIFY_DEPOSIT
        /// </summary>
        public string identify_deposit
        {
            get
            {
                return this._identify_deposit;
            }
            set
            {
                this._identify_deposit = value;
            }
        }
        
        /// <summary>
        /// COLUMN: SERVICE_FEE
        /// </summary>
        public string service_fee
        {
            get
            {
                return this._service_fee;
            }
            set
            {
                this._service_fee = value;
            }
        }
        
        /// <summary>
        /// COLUMN: IDENTIFY_REASON
        /// </summary>
        public string identify_reason
        {
            get
            {
                return this._identify_reason;
            }
            set
            {
                this._identify_reason = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEAL_RESULT
        /// </summary>
        public string deal_result
        {
            get
            {
                return this._deal_result;
            }
            set
            {
                this._deal_result = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
