//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8839
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T1.WS.Model.DB
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// 数据库表名称：tick_box_oper_info
    /// </summary>
    public class TickBoxOperInfo
    {
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        private string _line_id;
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        private string _station_id;
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        private string _device_id;
        
        /// <summary>
        /// COLUMN: OPER_SEQ
        /// </summary>
        private string _oper_seq;
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        private string _operator_id;
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        private string _run_date;
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        private string _occur_date;
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        private string _occur_time;
        
        /// <summary>
        /// COLUMN: OPER_TYPE
        /// </summary>
        private string _oper_type;
        
        /// <summary>
        /// COLUMN: DATA_TYPE
        /// </summary>
        private string _data_type;
        
        /// <summary>
        /// COLUMN: TICK_BOX_ID
        /// </summary>
        private string _tick_box_id;
        
        /// <summary>
        /// COLUMN: INSTALL_STATUS
        /// </summary>
        private string _install_status;
        
        /// <summary>
        /// COLUMN: BOX_LOCATION_TYPE
        /// </summary>
        private string _box_location_type;
        
        /// <summary>
        /// COLUMN: TICK_MANA_TYPE
        /// </summary>
        private string _tick_mana_type;
        
        /// <summary>
        /// COLUMN: TICK_STATUS
        /// </summary>
        private string _tick_status;
        
        /// <summary>
        /// COLUMN: TICK_NUM
        /// </summary>
        private string _tick_num;
        
        /// <summary>
        /// COLUMN: ORI_TICK_NUM
        /// </summary>
        private string _ori_tick_num;
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        private string _update_date;
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        private string _update_time;
        
        /// <summary>
        /// COLUMN: LINE_ID
        /// </summary>
        public string line_id
        {
            get
            {
                return this._line_id;
            }
            set
            {
                this._line_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: STATION_ID
        /// </summary>
        public string station_id
        {
            get
            {
                return this._station_id;
            }
            set
            {
                this._station_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DEVICE_ID
        /// </summary>
        public string device_id
        {
            get
            {
                return this._device_id;
            }
            set
            {
                this._device_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPER_SEQ
        /// </summary>
        public string oper_seq
        {
            get
            {
                return this._oper_seq;
            }
            set
            {
                this._oper_seq = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPERATOR_ID
        /// </summary>
        public string operator_id
        {
            get
            {
                return this._operator_id;
            }
            set
            {
                this._operator_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: RUN_DATE
        /// </summary>
        public string run_date
        {
            get
            {
                return this._run_date;
            }
            set
            {
                this._run_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_DATE
        /// </summary>
        public string occur_date
        {
            get
            {
                return this._occur_date;
            }
            set
            {
                this._occur_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OCCUR_TIME
        /// </summary>
        public string occur_time
        {
            get
            {
                return this._occur_time;
            }
            set
            {
                this._occur_time = value;
            }
        }
        
        /// <summary>
        /// COLUMN: OPER_TYPE
        /// </summary>
        public string oper_type
        {
            get
            {
                return this._oper_type;
            }
            set
            {
                this._oper_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: DATA_TYPE
        /// </summary>
        public string data_type
        {
            get
            {
                return this._data_type;
            }
            set
            {
                this._data_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_BOX_ID
        /// </summary>
        public string tick_box_id
        {
            get
            {
                return this._tick_box_id;
            }
            set
            {
                this._tick_box_id = value;
            }
        }
        
        /// <summary>
        /// COLUMN: INSTALL_STATUS
        /// </summary>
        public string install_status
        {
            get
            {
                return this._install_status;
            }
            set
            {
                this._install_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: BOX_LOCATION_TYPE
        /// </summary>
        public string box_location_type
        {
            get
            {
                return this._box_location_type;
            }
            set
            {
                this._box_location_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_MANA_TYPE
        /// </summary>
        public string tick_mana_type
        {
            get
            {
                return this._tick_mana_type;
            }
            set
            {
                this._tick_mana_type = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_STATUS
        /// </summary>
        public string tick_status
        {
            get
            {
                return this._tick_status;
            }
            set
            {
                this._tick_status = value;
            }
        }
        
        /// <summary>
        /// COLUMN: TICK_NUM
        /// </summary>
        public string tick_num
        {
            get
            {
                return this._tick_num;
            }
            set
            {
                this._tick_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: ORI_TICK_NUM
        /// </summary>
        public string ori_tick_num
        {
            get
            {
                return this._ori_tick_num;
            }
            set
            {
                this._ori_tick_num = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_DATE
        /// </summary>
        public string update_date
        {
            get
            {
                return this._update_date;
            }
            set
            {
                this._update_date = value;
            }
        }
        
        /// <summary>
        /// COLUMN: UPDATE_TIME
        /// </summary>
        public string update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
    }
}
